### ISSUE TITLE
fixed Icedtea-Web issues with trusted.jssecerts

### ISSUE THREAD

**Issue by patris70** [ojdkbuild/ojdkbuild#100]
Hi,

Icedtea-Web has Problem, because does not use trusted.jssecerts File and adds SSL certificate to trusted.certs File (as Info: trusted.certs File is for Code-Signing certificates). 
In Zip File is CertWarningPane.java and SecurityUtil.java Files (added trusted.jssecerts function)

[Files.zip](https://github.com/ojdkbuild/ojdkbuild/files/3578287/Files.zip)

**Comment by ojdkbuild** [comment]
Patch looks okay, but unless there is some user-facing issue with this file, I'd rather not change this certs handling.  It should not be that important, how exactly webstart stores its internal files. Closing as "won't fix".
