### ISSUE TITLE
changing the userdata folder

### ISSUE THREAD

**Issue by TheRaysor** [ojdkbuild/ojdkbuild#104]
Hi there!
I was wondering if i am able to change the directory of the userdata?
I wanted to save the my trusted configs in another folder, so i searched for the itw configs and i saw the variable wsdir an that the option -Ditw.userdata is changed to wsdir. Is there a way to use systemvariables like %appdata%

**Comment by ojdkbuild** [comment]
Closing the issue, please re-open if more assistance is needed on javaws_options.txt.
