### ISSUE TITLE
Travis

### ISSUE THREAD

**Issue by wafisher** [ojdkbuild/ojdkbuild#107]
Can I use this as the base for a Travis build? Currently Travis defaults to JDK 11.0.2. Not sure if I understand this repo though.

**Comment by ojdkbuild** [comment]
Moving the issue to the main repo.

Could you clarify, you would like to build the latest jdk11-linux as a first step of your Travis build? Or just use the latest jdk11-linux binaries for your build?

In the latter case, it may be easier to just do `curl -LO <url_to_jdk11.zip> && unzip ...`.

**Comment by wafisher** [comment]
I want an image with Java SDK 11.0.5 installed so that `./gradlew build` runs with 11.0.5. It sounds like at a minimum if I used this, I'd still have to install it i.e. set `JAVA_HOME` appropriately.

What's the purpose of the the CI build exactly?

**Comment by ojdkbuild** [comment]
I think `curl` + `unzip` + `export JAVA_HOME=path/to/jdk` should be enough for gradle.

CI build in contrib_jdk11u-ci repo builds vanilla OpenJDK for Linux directly from upstream sources. Build is done in CentOS 6 container so the resulting binaries require only the very old glibc version and are highly portable between different Linux distros.

**Comment by wafisher** [comment]
Awesome, thanks!
