### ISSUE TITLE
Silent installation java-1.8.0-openjdk-1.8.0.232-1.b09.ojdkbuild.windows.x86_64.msi

### ISSUE THREAD

**Issue by MiM4CZ** [ojdkbuild/ojdkbuild#109]
Hello,
version: java-1.8.0-openjdk-1.8.0.232-1.b09.ojdkbuild.windows.x86_64.msi.
How can I choose parameter in Dialog Files in use ...
Id like to choose Do not close application. A reboot will be required.

Where is problem ?

msiexec -i "java-1.8.0-openjdk-1.8.0.232-1.b09.ojdkbuild.windows.x86_64.msi" /norestart WixUIRMOption=DontUseRM

doesnt work -it kills opened application and property Do not close application. A reboot will be required isnt as default.

Thanks.

**Comment by ojdkbuild** [comment]
Hi, after some reading and experiments on this, I think the only option to do silent uninstall, without killing running java processes, is to setup the policy on the particular windows machine as [described here](https://groups.google.com/d/msg/tortoisesvn/qnFsEj_28o4/LRmpO6_MzwAJ).

Generally ojdkbuild installer doesn't do anything special about MSI reboot behaviour, and I'd rather keep it this way (with the default behaviour). Another similar issue - #42 .

**Comment by ojdkbuild** [comment]
Closing the issue as "wontfix (hard)".
