### ISSUE TITLE
ECMAScript engine not found with IcedTea-Web

### ISSUE THREAD

**Issue by ledahulevogyre** [ojdkbuild/ojdkbuild#110]
The following test prints "_jdk.nashorn.api.scripting.NashornScriptEngine@17faa95_" when running from the command line. But through IcedTea-Web, it prints "_null_".
```
    ScriptEngineManager manager = new ScriptEngineManager();
    System.out.println(manager.getEngineByName("ECMAScript"));
```
It seems that the nashorn JS engine is not accessible when running through IcedTea-Web.
You can run this test yourself [here](https://leunen.me/test.jnlp).

Is it something I should report to IcedTea-Web rather than here ?

Thanks.

**Comment by ojdkbuild** [comment]
Hi, thanks for the report, I can reproduce it.

It can be fixed adding `nashorn.jar` to boot classpath in `<jdk>/webstart/javaws_options.txt`:

    # other JVM options
    -splash:"{{localdir}}javaws_splash.png"
    -Xbootclasspath/a:"{{localdir}}javaws.jar;{{jdkdir}}jre/lib/ext/nashorn.jar"

Without adding it to bootclasspath direct access to Nashorn script engine won't work either:

    new NashornScriptEngineFactory().getScriptEngine()

I am not sure whether this is a "bug" or a "security feature", Nashorn generates bytecode that needs to be loaded at run time and ITW doesn't like it unless it is on boot classpath.

It may be useful to report this to upstream ITW to get their opinion on `javax.scripting` support.

**Comment by ledahulevogyre** [comment]
Thanks a lot.

**Comment by ojdkbuild** [comment]
Closing the issue, please re-open if problem persists.
