### ISSUE TITLE
Version of openjfx 8 

### ISSUE THREAD

**Issue by buedi** [ojdkbuild/ojdkbuild#112]
I'm running in a problem with big (quadratic) performance problem of javaFX. 
This bug([https://bugs.openjdk.java.net/browse/JDK-8209830](https://bugs.openjdk.java.net/browse/JDK-8209830)) was fixed for version 1.8.0 build 252 .
Please can you update the openjfx version? It looks like this is still openjfx-8.0.202.

**Comment by ojdkbuild** [comment]
Hi, thanks for the report, please note that 8u202 was the last public update for openjfx-8. Oracle updates after that are not public and upstream openjfx-8 project is inactive ([some details](http://mail.openjdk.java.net/pipermail/openjfx-dev/2019-May/023299.html)).

This project builds latest public openjfx-8u202 sources + later security patches backported from openjfx-current (latest is 8u252-1: [x86_64](https://github.com/ojdkbuild/ojdkbuild/releases/tag/java-1.8.0-openjdk-1.8.0.252-1.b09), [x86](https://github.com/ojdkbuild/ojdkbuild/releases/tag/java-1.8.0-openjdk-1.8.0.252-1.b09-x86)). Some non-security fixes were also included, like the fix to websockets in webview.

I can backport this patch and re-spin 8u252 with it, just it would be great to get some help with verifying that it does not break other CSS logic (like it [happened with previous fix to that issue](https://bugs.openjdk.java.net/browse/JDK-8193445?focusedCommentId=14298411&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14298411)).

**Comment by buedi** [comment]
Thanks for this answer. It would be great if you make this bugfix backported. Because it has a significant influence to the usage after 1.8.0u121.
This backported fix looks working stable [Backport to 8u251](https://bugs.openjdk.java.net/browse/JDK-8234898)
Bugfix --> https://github.com/openjdk/jfx/pull/34

**Comment by buedi** [comment]
With the new release(1.8.0u252-2) this JavaFX performance bug is fixed! Thanks a lot!

**Comment by ojdkbuild** [comment]
Thanks for verifying!

I included the test into the [backport](https://github.com/ojdkbuild/upstream_openjfx-8u/commit/b73cd319caf774f61c487ac0ae1b792f53062b76)and checked that it is passing, but was unable to actually trigger a failure with this test on unpatched version.

Closing the issue, please re-open if it appeared that this patch breaks something in CSS handling.
