### ISSUE TITLE
How to add intrinsic functions to jdk ? Like Simd AVX512?

### ISSUE THREAD

**Issue by eix128** [ojdkbuild/ojdkbuild#113]
Hi , i want to add intrinsic SIMD functions like AVX512 to JVM.
I dont know where to patch or add functions ? 
is there any clue can you give ?

**Comment by ojdkbuild** [comment]
Hi, I suggest starting with [Volker Simonis presentations](https://www.youtube.com/results?search_query=volker+simonis+intrinsics) about intrinsics. Also this [maillist thread](http://mail.openjdk.java.net/pipermail/hotspot-compiler-dev/2018-August/030202.html) may be helpful.

**Comment by ojdkbuild** [comment]
Closing the issue, please reopen if needed.
