### ISSUE TITLE
JFX Question

### ISSUE THREAD

**Issue by patris70** [ojdkbuild/ojdkbuild#115]
Hi,

Which higher OpenJFX Version works correctly with OpenJDK8u Version?
Can I use a higher OpenJFX Version with OpenJDK8u?
If yes, which OpenJFX Version?
I ask because there is no more Update for OpenJFX8u.

Thanks

**Comment by ojdkbuild** [comment]
Hi, if you mean OpenJFX 9 and later, then it is not possible to use them with OpenJDK 8u. In 8u OpenJFX is just an "overlay" - a set of files, that can be dropped on top of OpenJDK 8u directory. Due to modules system introduced in 9, such "overlay" is not possible in 9+ and OpenJFX becomes a set of JPMS modules. In 11+ these modules are standalone - not part of OpenJDK distribution. Hope this answers the question.

Also see [some details](https://github.com/ojdkbuild/ojdkbuild/issues/112#issuecomment-616455091) on OpenJFX 8u handling in this project.

**Comment by patris70** [comment]
Hi,

Thanks, i used your OpenJFX8u Bug fixes in my OpenJDK8u.
If understood correctly, you will always fix bugs in your OpenJFX in the future, right?

One more question, can you please tell me which OpenJFX Version can be used with which OpenJDK Version?

Thanks

**Comment by ojdkbuild** [comment]
> If understood correctly, you will always fix bugs in your OpenJFX8u in the future, right?

Unfortunately my employer Red Hat doesn't provide commercial support for OpenJFX, so OpenJFX 8u in this project is updated on "best effort" basis. I'm trying to backport all security issues promptly and some additional fixes if they look critical. With the mainline OpenJFX effectively being in maintenance mode for many years now, I hope to be able to continue with 8u backports in future. But there is a good chance, that some big incompatible security related fix will be added to mainline OpenJFX and it will be not possible to backport it to 8u in this project. The most scary part is WebKit security updates (huge actively developed codebase), but during last two years there were multiple WebKit updates that were relatively easy to backport so far.

> One more question, can you please tell me which OpenJFX Version can be used with which OpenJDK Version?

M, if you mean the same major versions between different vendors - then OpenJFX 8u can be just dropped upon any recent version of OpenJDK 8u and OpenJFX 11+ modules should work fine with corresponding 11+ OpenJDK from any vendor. If you mean using OpenJFX from one major version with OpenJDK from another - it definitely won't work with OpenJDK 8, it probably won't work with 11+ modules too.

**Comment by patris70** [comment]
Thanks for first Answer.

I mean mit second question (OpenJFX Version requirement for OpenJDK Version), for Example:

OpenJDK 9 with OpenJFX 10 or OpenJDK 11 with OpenJFX 14 and other. I need just know, which OpenJDK Version with OpenJFX Version must using?

I found just this Info for JFX 14 (that mean can JFX 14 using with JDK11 or 14):
 _For both options, it is required to have a recent version of JDK 14, or at least JDK 11._ 

`https://openjfx.io/openjfx-docs/`

Thanks

**Comment by ojdkbuild** [comment]
I really don't know whether OpenJFX 14 is compatible with OpenJDK 11 or not, I would expect it to be compatible only with 14. I stopped building OpenJFX after 10 so don't have first hand knowledge about new versions. I can suggest reaching out to OpenJFX upstream people with this question - Johan Vos et al.

**Comment by patris70** [comment]
Thanks so much for clear answers.
You can close topic.

Best regards
