### ISSUE TITLE
No JFX mixin in java-1.8.0-openjdk-1.8.0.262-1.b10-vs15?

### ISSUE THREAD

**Issue by mimenz** [ojdkbuild/ojdkbuild#116]
Hi there,
will there be a 64bit-mixin of OpenJFX for OpenJDK8_262?
Thanks a lot,
Michael

**Comment by ojdkbuild** [comment]
Hi, I've just added 8u262 x86_64 with OpenJFX - [link](https://github.com/ojdkbuild/ojdkbuild/releases/tag/java-1.8.0-openjdk-1.8.0.262-1.b10). I've also removed "-vs15" release that doesn't contain OpenJFX.

**Comment by mimenz** [comment]
That was fast, thanks!
