### ISSUE TITLE
Invalid 'java.vendor' property in java 11.0.8+10-LTS

### ISSUE THREAD

**Issue by yshupletsov** [ojdkbuild/ojdkbuild#117]
Use latest centos 8.2.
Run 'yum install java-11-openjdk'.
Package java-11-openjdk-11.0.8.10-0.el8_2.x86_64 is installed.
Run 'java -XshowSettings:properties -version'.
You can see there 'java.vendor = N/A'.
Is it a bug? It's important for me to get the vendor of installed java.

**Comment by ojdkbuild** [comment]
Hi, this looks a bit weird, I know this property was [added to Fedora](https://src.fedoraproject.org/rpms/java-11-openjdk/blob/master/f/java-11-openjdk.spec#_1506), it is also added to [ojdkbuild builds](https://github.com/ojdkbuild/ojdkbuild/blob/master/src/java-11-openjdk/CMakeLists.txt#L195). But [in CentOS](https://git.centos.org/rpms/java-11-openjdk/blob/c8/f/SPECS/java-11-openjdk.spec#_1518) it is not added for some reason. I assume it is going to be propagated there from Fedora with the next update in October.

**Comment by yshupletsov** [comment]
Hi, thanks!
Can i get version with fix earlier (using AppStream) than October?

**Comment by imorph** [comment]
Hello @ojdkbuild!

Is it possible that it is related to: https://hg.openjdk.java.net/jdk/jdk/rev/dff3aabdc2f3 ?
looks like here: https://src.fedoraproject.org/rpms/java-11-openjdk/blob/master/f/java-11-openjdk.spec#_1506
we have comma in `--with-vendor-name`

**Comment by yshupletsov** [comment]
Another question - what is the best way to get information about vendor? Because, instead of 'java.vendor', 'java.vm.vendor' parameter is still 'Oracle Corporation'.

**Comment by ojdkbuild** [comment]
@imorph , @yshupletsov , sorry for the lack of info here, I cannot really comment on CentOS jdk builds, because they are basically RHEL builds and I don't want to comment on RHEL in public. If you by chance have a RHEL subscription - I can comment in RH support case instead.

About the comma problem, IIRC it was fixed promptly and comma in vendor props works now in all versions.

The properties for Fedora should look this way:

    java.specification.vendor = Oracle Corporation
    java.specification.version = 1.8
    java.vendor = Red Hat, Inc
    java.vendor.url = https://www.redhat.com/
    java.vendor.url.bug = https://bugzilla.redhat.com/enter_bug.cgi?product=Fedora&component=java-1.8.0-openjdk&version=31
    java.version = 1.8.0_265
    java.vm.info = mixed mode
    java.vm.name = OpenJDK 64-Bit Server VM
    java.vm.specification.name = Java Virtual Machine Specification
    java.vm.specification.vendor = Oracle Corporation
    java.vm.specification.version = 1.8
    java.vm.vendor = Red Hat, Inc

And for ojdkbuild the expected output is:

    java.specification.vendor = Oracle Corporation
    java.specification.version = 1.8
    java.vendor = ojdkbuild
    java.vendor.url = https://github.com/ojdkbuild
    java.vendor.url.bug = https://github.com/ojdkbuild/ojdkbuild/issues
    java.version = 1.8.0_265
    java.vm.info = mixed mode
    java.vm.name = OpenJDK 64-Bit Server VM
    java.vm.specification.name = Java Virtual Machine Specification
    java.vm.specification.vendor = Oracle Corporation
    java.vm.specification.version = 1.8
    java.vm.vendor = ojdkbuild

I am closing this, because ojdkbuild output seems to be correct to me, please reopen if you have more questions.
