### ISSUE TITLE
Issue launching jnlp from ibm https://www.ibm.com/support/fixcentral/dldirector/installation_en.html

### ISSUE THREAD

**Issue by svstrain** [ojdkbuild/ojdkbuild#118]
Starting Netx, command: ["C:/Program Files/ojdkbuild/java-1.8.0-openjdk-1.8.0.252-2/webstart/../jre/bin/java.exe" -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -XX:+UseSerialGC -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -splash:"C:/Program Files/ojdkbuild/java-1.8.0-openjdk-1.8.0.252-2/webstart/javaws_splash.png" -Xbootclasspath/a:"C:/Program Files/ojdkbuild/java-1.8.0-openjdk-1.8.0.252-2/webstart/javaws.jar" -classpath "C:/Program Files/ojdkbuild/java-1.8.0-openjdk-1.8.0.252-2/webstart/../jre/lib/rt.jar" -Ditw.userdata="C:/Users/sstrain/AppData/Local/ojdkbuild/java-1.8.0-openjdk-1.8.0.252-2.b09.ojdkbuild.windows.x86_64/webstart/" -Dicedtea-web.bin.name=javaws.exe -Dicedtea-web.bin.location="C:/Program Files/ojdkbuild/java-1.8.0-openjdk-1.8.0.252-2/webstart/javaws.exe" net.sourceforge.jnlp.runtime.Boot -Xnofork -helpurl="https://github.com/ojdkbuild/ojdkbuild/wiki/WebStart" "C:\temp\IBM_Install_DD.jnlp"]
Unable to use Firefox's proxy settings. Using "DIRECT" as proxy type.
You are trying to get resource https://www.ibm.com/support/fixcentral/dldirector/splash.gif but it is not in cache and could not be downloaded. Attempting to continue, but you may expect failure
You are trying to get resource https://www.ibm.com/support/fixcentral/dldirector/dldirector.jar but it is not in cache and could not be downloaded. Attempting to continue, but you may expect failure
JAR https://www.ibm.com/support/fixcentral/dldirector/dldirector.jar not found. Continuing.
JAR https://www.ibm.com/support/fixcentral/dldirector/dldirector.jar not found. Continuing.
netx: Initialization Error: Could not initialize application. (Fatal: Initialization Error: Unknown Main-Class. Could not determine the main class for this application.)
net.sourceforge.jnlp.LaunchException: Fatal: Initialization Error: Could not initialize application. The application has not been initialized, for more information execute Netx directly from the command line.
	at net.sourceforge.jnlp.Launcher.createApplication(Launcher.java:822)
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:531)
	at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:945)
Caused by: net.sourceforge.jnlp.LaunchException: Fatal: Initialization Error: Unknown Main-Class. Could not determine the main class for this application.
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.initializeResources(JNLPClassLoader.java:774)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.<init>(JNLPClassLoader.java:338)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.createInstance(JNLPClassLoader.java:421)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.getInstance(JNLPClassLoader.java:495)
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.getInstance(JNLPClassLoader.java:468)
	at net.sourceforge.jnlp.Launcher.createApplication(Launcher.java:814)
	... 2 more

**Comment by btreut** [comment]
I am not shure if it helps, but it may be a problem with a proxy. Afaik [OpenWebstart ](https://openwebstart.com/)has an imporved handling of proxy settings, so I think it is worth a try ...

**Comment by ojdkbuild** [comment]
Hi, sorry for the delayed response. When I am running "IBM_Install_DD.jnlp" from [here](https://www-03.ibm.com/isc/esd/dswdown/dldirector/installation_en.html), it runs successfully for me (Win10 + 8u256 MSI).

"JAR <url> not found. Continuing." from your trace means that ITW cannot download these resources. I also think the proxy may be the problem here, assuming proxy is used in your env. ITW-1.8 in this project supports proxies (including PAC and reading Firefox proxy settings), but ITW latest versions from OpenWebStart may indeed include better proxy support.

If you provide the details about proxy config in your env, I can possibly help with configuring ITW for it.

**Comment by svstrain** [comment]
Must be proxy.

Thanks,
-S

**Comment by ojdkbuild** [comment]
Closing the issue, please reopen if needed.
