### ISSUE TITLE
java.exe pdb missing

### ISSUE THREAD

**Issue by eli-fin** [ojdkbuild/ojdkbuild#119]
Hi,

The debuginfo zip does contain a java.pdb file, but it looks like it's the one for "jre\bin\java.dll" rather than java.exe.
I didn't look through the build scripts. Maybe one of them is overwritten because they have the same name.

**Comment by ojdkbuild** [comment]
Thanks for the report! This looks to be a real bug. Logic for debuginfo copying is non-trivial, [this bit seems to be related](https://github.com/ojdkbuild/lookaside_java-1.8.0-openjdk/blob/master/jdk/make/Images.gmk#L152), I will follow up on this.

**Comment by ojdkbuild** [comment]
PDB for `java.exe` launcher was added to [11 debuginfo](https://github.com/ojdkbuild/ojdkbuild/releases/tag/java-11-openjdk-11.0.9.11-2) as an additonal file (with `_EXE` suffix). This was not yet done for 8 (build logic there is different), keeping the issue open for that.

**Comment by ojdkbuild** [comment]
Added PDB for java.exe to [8 debuginfo](https://github.com/ojdkbuild/ojdkbuild/releases/tag/java-1.8.0-openjdk-1.8.0.282-1.b08) too, closing the issue.
