### ISSUE TITLE
How to get jdk sources for each build?

### ISSUE THREAD

**Issue by eli-fin** [ojdkbuild/ojdkbuild#120]
Hi,

When downloading a specific debug build, how can I get a snapshot of the sources used for that build?

The github release has a "Source code" link, but it's for the sources of this repo, not the JDK.
It might be a waste of space to store a zip of the sources for each build, but the repo and commit hash should suffice I think.

Without it, it's pretty difficult and tedious to debug the native code reliably

**Comment by eli-fin** [comment]
Just noticed that jdk sources are in a submodule.
Not very familiar with those. If I clone the repo recursively will I get the correct commit for all submodules?

**Comment by ojdkbuild** [comment]
Hi, the following should work without cloning the whole forest:

    git clone https://github.com/ojdkbuild/ojdkbuild.git
    cd ojdkbuild
    git checkout <appropriate release tag>
    # jdk8
    git submodule update --init lookaside/java-1.8.0-openjdk
    # jdk11
    git submodule update --init lookaside/java-11-openjdk
    # jdk-latest
    git submodule update --init lookaside/jdk
