### ISSUE TITLE
When will jdk8u272 be released?

### ISSUE THREAD

**Issue by ultimatesecpro** [ojdkbuild/ojdkbuild#121]
Could you please update when jdk8u272 will be released?

**Comment by ojdkbuild** [comment]
Yes, it is being prepared right now and there are minor problems, I expect to publish it during this weekend.

**Comment by ultimatesecpro** [comment]
Thank you very much for the prompt reply!
Good luck with the build!

**Comment by ojdkbuild** [comment]
x86_64 build is ready - [link](https://github.com/ojdkbuild/ojdkbuild/releases/tag/java-1.8.0-openjdk-1.8.0.272-1.b10), other builds will follow shortly.

**Comment by ojdkbuild** [comment]
8u275 update (with some critical fixes) is going be released in a day or two,  see [details](https://mail.openjdk.java.net/pipermail/jdk8u-dev/2020-November/012949.html), re-opening the issue for visibility. 11.0.9 also going to be updated.

**Comment by Saxomania** [comment]
for 11.0.9 MSI is missing

**Comment by ojdkbuild** [comment]
Yes, 11.0.9.1 is delayed because Azure Pipelines build keep failing for unclear reason, while it works fine locally - https://dev.azure.com/ojdkbuild/ojdkbuild/_build/results?buildId=119&view=results 

Looking into that

**Comment by ojdkbuild** [comment]
11.0.9.1 is built now ([link](https://github.com/ojdkbuild/ojdkbuild/releases/tag/java-11-openjdk-11.0.9.11-2)) and readme is updated, closing the issue.
