### ISSUE TITLE
Convert ojdkbuild to an organization

### ISSUE THREAD

**Issue by RDIL** [ojdkbuild/ojdkbuild#122]
Hi!  
I just noticed that on GitHub, @ojdkbuild is a user.  I feel like it would be more productive for it to be an organization, so that all the maintainers can use teams to collaborate, and organizations have a much better permission system.  Thankfully, GitHub now has a way to turn your user into an organization in settings easily, so that might be worth while looking into.

Just my two cents.
Thanks in advance!

**Comment by ojdkbuild** [comment]
Hi, thanks for suggestion, I don't have a strong opinion on this, just it seems to be unnecessary. I can review/merge a PR if one appears in the current setup. And conversion of an account to organization is irreversible.

I guess nowadays the majority of github activity should be done in https://github.com/openjdk org anyway. So I will leave this account as a "user account" for now.

**Comment by ojdkbuild** [comment]
Closing the issue, will keep it as "user account" for now.
