### ISSUE TITLE
compilation

### ISSUE THREAD

**Issue by awesomennguy** [ojdkbuild/ojdkbuild#123]
hi, is there any docs how to compile this?

**Comment by ichaus-we** [comment]
https://github.com/ojdkbuild/ojdkbuild/wiki/HowToBuild

**Comment by ojdkbuild** [comment]
Yes, this doc is valid. Just if you are looking into building jdk11+ and don't need installer - it may be easier to start here - https://github.com/openjdk/jdk/blob/master/doc/building.md .

**Comment by awesomennguy** [comment]
and is it possible to compile just one file? (java.dll, etc)
(btw wow i just saw this is #123 thread nice)

**Comment by ojdkbuild** [comment]
It is possible in theory to build only the HotSpot VM - `jvm.dll` (for embedding into other apps) without building class library. But the easiest way will be to do a full build (`make images`) and then to strip the images as needed.

Closing the issue, please feel free to reopen if needed.

**Comment by awesomennguy** [comment]
Hi, so I read the wiki and now I have this. Do you know what to do?
Building OpenJDK ...
java-1.8.0-openjdk/../../lookaside/java-1.8.0-openjdk/configure: line 24: $'\r': command not found
java-1.8.0-openjdk/../../lookaside/java-1.8.0-openjdk/configure: line 27: $'\r': command not found
java-1.8.0-openjdk/../../lookaside/java-1.8.0-openjdk/configure: line 30: cd: (it is wrong path): No such file or directory/java-1.8.0-openjdk/../../lookaside/java-1.8.0-openjdk
java-1.8.0-openjdk/../../lookaside/java-1.8.0-openjdk/configure: line 31: $'\r': command not found
/make/autoconf/configure: No such file or directory
