### ISSUE TITLE
compilation

### ISSUE THREAD

**Issue by awesomennguy** [ojdkbuild/ojdkbuild#124]
Hi, so I read the wiki and now I have this. Do you know what to do?
Building OpenJDK ...
java-1.8.0-openjdk/../../lookaside/java-1.8.0-openjdk/configure: line 24: $'\r': command not found
java-1.8.0-openjdk/../../lookaside/java-1.8.0-openjdk/configure: line 27: $'\r': command not found
java-1.8.0-openjdk/../../lookaside/java-1.8.0-openjdk/configure: line 30: cd: (it is wrong path): No such file or directory/java-1.8.0-openjdk/../../lookaside/java-1.8.0-openjdk
java-1.8.0-openjdk/../../lookaside/java-1.8.0-openjdk/configure: line 31: $'\r': command not found
/make/autoconf/configure: No such file or directory

(maybe same issue #111)

**Comment by ojdkbuild** [comment]
Yes, seems to be the same issue with `core.autocrlf`, this needs to be added to HowToBuild page, as `true` is used by default in win-git for some reason.

Please try to redo the checkout with `false` option.

**Comment by awesomennguy** [comment]
It still doesn't work.

**Comment by ojdkbuild** [comment]
It should work with `core.autocrlf=false`, just the checkout needs to be done again. Can you post the problem you are seeing (if problem is the same - then the steps you are doing)?

**Comment by awesomennguy** [comment]
Turning off autocrlf helped, you probably should add steps from #111 to build-wiki, but anyways thank you for help!

**Comment by awesomennguy** [comment]
And is there any page how to import java jdk to ide?

**Comment by awesomennguy** [comment]
IDEs such as Visual Studio etc

**Comment by ojdkbuild** [comment]
For native code on Linux it should work, please see this [config example](https://github.com/akashche/wiki/wiki/AArch32RemoteDebug#build-from-netbeans) (excluding ARM32 details). For native code on Windows - I don't think there is any working support for Visual Studio.

For java code - there is no main project for the whole JDK. There are some project files in source tree for some of the JDK parts that may provide some support.

Latest version of jdk16 may have substantially better support for IDEs - there were some activity on IDE support over time. But I don't think it has some "main" project for the full JDK.

**Comment by awesomennguy** [comment]
anyways thank you
