### ISSUE TITLE
Use icedtea-web from the new source

### ISSUE THREAD

**Issue by fennibay** [ojdkbuild/ojdkbuild#125]
icedtea-web was moved from https://icedtea.classpath.org/wiki/IcedTea-Web to github https://github.com/AdoptOpenJDK/IcedTea-Web and is now being maintained there, but ojdkbuild is still using an older version cloned at https://github.com/ojdkbuild/lookaside_icedtea-web

Are there any plans to move to using the latest upstream?

Specifically, I need the fix in https://github.com/AdoptOpenJDK/IcedTea-Web/pull/679, but this PR not merged to the currently used lookaside_icedtea-web

Many thanks for maintaining this package.

**Comment by ojdkbuild** [comment]
Hi, thanks for the report!

IcedTea-Web build in this project predates the "modern" ITW on AdoptOpenJDK (wth Windows support etc). Unfortunately there are no plans for major ITW updates for jdk8 of for adding ITW to jdk11+ in this project. This ITW remains in a "deep maintenance". 

Though the specific patch you pointed out looks to be small and non-intrusive. I've [backported it](https://github.com/ojdkbuild/lookaside_icedtea-web/commit/a754cac3c68ad24d60ce04826ab0cc13d989147a) and it is going to be included with the upcoming 8u282 release.

If you can look at [this pre-release build](https://drive.google.com/file/d/1fWJhMyZZ1I2RVDjrmpU2HFxSAJcW9Gdq/view?usp=sharing) (EA, does NOT include 8u282 security fixes) to check whether the patch fixes the actual problem - that would be great.

**Comment by fennibay** [comment]
Hi, many thanks for the quick fix. Do you also have a zipped build instead of MSI?

**Comment by ojdkbuild** [comment]
Uploaded the ZIP with the same files as MSI above (excluding Mission Control) - https://drive.google.com/file/d/1eXw08ujrVKQkY5ucyd2wRLmzexHhA6aw/view?usp=sharing

**Comment by fennibay** [comment]
Thank you. I just tried with 1.8.0.282-0 and the problem seems to be fixed.

To make sure I also tried again with 1.8.0.275-1, and could reproduce the problem with that.

So, it looks good. Thanks again!

**Comment by ojdkbuild** [comment]
Sure, thanks for confirming, feel free to close it. Release version of 8u282 should be ready around the end of next week.
