### ISSUE TITLE
Automatically link Jar file accociation in installer

### ISSUE THREAD

**Issue by RDIL** [ojdkbuild/ojdkbuild#126]
So I am on Windows, and whenever I update my ojdkbuild version, Jar files become unusable.  Windows no longer knows how to handle them, most likely because the previous executable location will no longer exist.
One solution is to use the amazing [Jarfix](https://johann.loefflmann.net/en/software/jarfix/index.html) tool, but it is tedious to do it every time.  The installer should have an option to automatically do this to save users the hassle.  
Thanks in advance!

**Comment by ojdkbuild** [comment]
Hi, thanks for the report. Unless I missing something about the use case, this is supposed to work. There is an installer option `jdk_registry_jar` that registers JAR for double-click and right-click (implemented in #33 ). And once installed, this feature should be enabled automatically on update (unless you are doing uninstall/reinstall - then it needs to be selected manually on reinstall).

**Comment by RDIL** [comment]
Oh, that explains it.  Thanks!
