### ISSUE TITLE
Proxy (WPAD) with Java Web Start (iced tea web)

### ISSUE THREAD

**Issue by Saxomania** [ojdkbuild/ojdkbuild#129]
may i am blind but i cant get done with OpenJDK 8u282 x86 itself...

always getting this error

Starting Netx, command: ["C:/Program Files (x86)/ojdkbuild/java-1.8.0-openjdk-1.8.0.282-1/webstart/../jre/bin/java.exe" -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -XX:+UseSerialGC -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -splash:"C:/Program Files (x86)/ojdkbuild/java-1.8.0-openjdk-1.8.0.282-1/webstart/javaws_splash.png" -Xbootclasspath/a:"C:/Program Files (x86)/ojdkbuild/java-1.8.0-openjdk-1.8.0.282-1/webstart/javaws.jar" -classpath "C:/Program Files (x86)/ojdkbuild/java-1.8.0-openjdk-1.8.0.282-1/webstart/../jre/lib/rt.jar" -Ditw.userdata="C:/Users/winad06/AppData/Local/ojdkbuild/java-1.8.0-openjdk-1.8.0.282-1.b08.ojdkbuild.windows.x86/webstart/" -Dicedtea-web.bin.name=javaws.exe -Dicedtea-web.bin.location="C:/Program Files (x86)/ojdkbuild/java-1.8.0-openjdk-1.8.0.282-1/webstart/javaws.exe" net.sourceforge.jnlp.runtime.Boot -Xnofork -helpurl="https://github.com/ojdkbuild/ojdkbuild/wiki/WebStart" "C:\Users\username\AppData\Local\Temp\2\20210213080725518.jnlp"]
Unable to use Firefox's proxy settings. Using "DIRECT" as proxy type.

this device is an Windows Server 2012 R2 with no direct internet access - only via proxy is allowed and we use wpad config url.
Browsing internet itself is not a problem at all.

I installed "iced tea web 1.8.4" (additionally to OpenJDK 8u282 x86) and after changing proxy settings with "itweb-settings.exe" -> network -> "automatic proxy configuration script" i had to set in firefox handle jnlp with iced tea web's "javaws.exe" and it works like it should. Deployment.properties inside my user profile looks like this:

deployment.proxy.auto.config.url=http\://wpad.xyz.xy/wpad.dat
deployment.proxy.type=2

Just to mention: running on a windows client with direct internet access "OpenJDK 8u282 x86" webstart is working also quite well
so it must be something with the Wpad proxy. Checked "C:\Program Files (x86)\ojdkbuild\java-1.8.0-openjdk-1.8.0.282-1\jre\lib\net.properties" but there seems no way to handle wpad proxy scripts.
Just for trying i added the proxy settings from iced tea web to the "net.properties" but no luck with that.
Even if i set our proxy direct in "net.properties" its not working for iced tea web integrated in OpenJDK. So it seems the OpenJDK integrated iced tea web doesnt seem to use the "net.properties".

I would like to have only OpenJDK installed and not IcedTeaWeb also because i dont want to have both installed and i dont know how well "Iced tea web" is maintained (last update was in April 2020).

is there any way to have the "itweb-settings.exe" as well for OpenJDK? Or how can i achieve to have wpad proxy (or even only default proxy support) for OpenJDK integrated iced tea web?

Thanks Sascha

**Comment by Saxomania** [comment]
really no answer within 2 weeks? Shouldnt be that special or?

**Comment by ojdkbuild** [comment]
Sorry for the delay with the response. PAC proxy is definitely works with this ITW build, but I am not sure about WPAD - never used it. Note, that deployment.properties need to be placed into "%LOCALAPPDATA%\ojdkbuild\java-1.8.0-openjdk-[version]\webstart\config\icedtea-web" directory. There is no launcher for settings GUI included, so deployment.properties needs to be prepared manually.

**Comment by Saxomania** [comment]
Got it and it works great
Just for documentation, this in the content of my deployment.properties:

`#Netx deployment configuration
#Sat Feb 13 08:20:31 CET 2021
deployment.jre.dir=C\:\\Program Files (x86)\\ojdkbuild\\java-1.8.0-openjdk-1.8.0.282-1\\jre
deployment.proxy.auto.config.url=http\://wpad.ServerURL.de/wpad.dat
deployment.proxy.type=2
deployment.security.level=DENY_UNSIGNED`
