### ISSUE TITLE
OpenJFX Integration

### ISSUE THREAD

**Issue by buedi** [ojdkbuild/ojdkbuild#13]
Is it planned to integrate OpenJFX to this build project?

**Comment by ojdkbuild** [comment]
Hi, no OpenJFX inclusion is not planned. To be included in this project OpenJFX first needs to be added to RHEL/CentOS and AFAIK there are no plans to add it there.

**Comment by ojdkbuild** [comment]
This issue is a duplicate of https://github.com/ojdkbuild/ojdkbuild/issues/6 , OpenJFX build is going to be tracked there.
