### ISSUE TITLE
Build JRE

### ISSUE THREAD

**Issue by awesomennguy** [ojdkbuild/ojdkbuild#130]
Hi is it possible to build JRE only?

**Comment by ojdkbuild** [comment]
Hi, no, that is not possible. JRE for 8 is bundled only after the full JDK is built. And for 11+ JRE is created with jlink also after all jmods are built.

**Comment by awesomennguy** [comment]
And can you provide some actions I can do to build specific images (for example java.exe, java.dll, jvm.dll, etc)?

**Comment by ojdkbuild** [comment]
I can suggest just to build the full image ("make images" jdk makefile target) and then get the bits you need from there.

Overall, if you are doing anything custom, it may be easier to do it with vanilla OpenJDK from https://github.com/openjdk , this project has a layer of build scripts on top of that and may be harder to customize.

**Comment by awesomennguy** [comment]
What do you mean "make images" jdk makefile target? Should I use "make images" in hotspot folder or what?

And I already tried to compile OpenJDK but it prints out GNU Make isn't installed, but I already installed it.

**Comment by ojdkbuild** [comment]
I mean jdk top-level (from jdk sources root) make target "make images". Depending how exactly you compile and what jdk version - there may be differences.

Closing the issue, please re-open if needed.
