### ISSUE TITLE
Unable to install latest version in W10

### ISSUE THREAD

**Issue by lmarcosd** [ojdkbuild/ojdkbuild#132]
Hello,

I've tried to install latest version of msi file in W10 and Windows defender smartscreen did come up with a message saying it's an unrecognized application, so it didn't allow starting it up. The message says "Unknown publisher"

I did have a previous version of the msi installer in my machine and it did work successfully, but not with new downloaded files.

Luis

**Comment by ojdkbuild** [comment]
Hi, I've tried 8u292 installer with Win10 and it worked for me after a number of warning screens. These warnings are not convenient, but installers needs to be signed my Microsoft certificate to avoid that, and that is not possible for these builds. It aslo may be possible, that Windows can completely block unsigned MSI installation depending on Windows settings. If signing is critical, then very similar installer can be downloaded [from Red Hat](https://developers.redhat.com/products/openjdk/download), it is signed, but downloads there require registration.

**Comment by lmarcosd** [comment]
ok, thanks a lot

**Comment by ojdkbuild** [comment]
Closing the issue, please reopen if needed.
