### ISSUE TITLE
java-1.8.0-openjdk-1.8.0.302-1.b08  --> x64 version is missing

### ISSUE THREAD

**Issue by Saxomania** [ojdkbuild/ojdkbuild#133]
debug version exists but without debug not. May i missed something?

**Comment by ojdkbuild** [comment]
Hi, sorry for delay, 64-bit 8u is handled separately from other
builds, it is already built and is waiting to be updated, should be
there tomorrow.

**Comment by Saxomania** [comment]
thanks

**Comment by ojdkbuild** [comment]
Uploaded now - https://github.com/ojdkbuild/ojdkbuild/releases/tag/java-1.8.0-openjdk-1.8.0.302-1.b08
