### ISSUE TITLE
OpenSSL 1.1 support for Java 1.8.0?

### ISSUE THREAD

**Issue by robert-scheck** [ojdkbuild/ojdkbuild#134]
The lookaside OpenSSL seems to be OpenSSL 1.0.2…is there any chance for OpenSSL 1.1 support for Java 1.8.0 to achieve TLSv1.3 support? CentOS/RHEL 8 seems to use OpenSSL 1.1 for Java 1.8.0, thus it likely works with less effort?

**Comment by ojdkbuild** [comment]
Hi, this part is a bit confusing: 

1. note that OpenSSL is NOT used by OpenJDK itself, it is used only by the update utility in installer that needs to fetch the update info without spawning a JVM

2. TLS 1.3 is supported in OpenJDK 8, IIRC it was added in 8u272, see [JDK-8248721](https://bugs.openjdk.java.net/browse/JDK-8248721) for details

3. OpenSSL in a lookaside repo (for update utility) follows the openssl RPM from RHEL/CentOS 7 (not 8), version 1.0.2.k (with additional patches) is the latest [available there](https://git.centos.org/rpms/openssl/commits/c7)

Hope this helps.

**Comment by ojdkbuild** [comment]
Closing the issue, please reopen if needed.

**Comment by robert-scheck** [comment]
Thank you very much for the clarification.
