### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by Princekin** [ojdkbuild/ojdkbuild#135]
![werwer](https://user-images.githubusercontent.com/70045520/128399595-ef795b8a-c148-44fc-a6ae-98cac3d9f1df.PNG)

Happens when trying to build **java-1.8.0-openjdk-1.8.0.302-1.b08**

**Comment by phoenixwy** [comment]
I also get same error.  

Does this issue occurs in latest JDK version ?

**Comment by ojdkbuild** [comment]
Hi, this looks to be related to windows `\r\n` line endings, `core.autocrlf=false` needs to be set before the checkout, see some [more details](https://github.com/ojdkbuild/ojdkbuild/issues/12#issuecomment-282592185).

**Comment by Princekin** [comment]
I already set `core.autocrlf=false` but the problem still.

**Comment by ojdkbuild** [comment]
Closing the issue, please reopen if needed.
