### ISSUE TITLE
Failure when building OpenJDK17

### ISSUE THREAD

**Issue by xWhitey** [ojdkbuild/ojdkbuild#137]
error: bad name in value for --add-modules option: 'c:\ojdkbuild\build\openjdk\support\gensrc\*;c:\ojdkbuild\lookaside\java-17-openjdk\src\*\windows\classes;c:\ojdkbuild\lookaside\java-17-openjdk\src\*\share\classes'
error: module not found: jdk.localedata
error: module not found: jdk.security.jgss
error: module not found: jdk.naming.dns
error: module not found: jdk.jpackage
error: module not found: jdk.jartool
error: module not found: jdk.accessibility
error: module not found: jdk.jdeps
error: module not found: jdk.dynalink
error: module not found: jdk.security.auth
error: module not found: jdk.nio.mapmode
error: module not found: jdk.management
error: module not found: jdk.incubator.foreign
error: module not found: jdk.jdwp.agent
error: module not found: jdk.jlink
error: module not found: java.smartcardio
error: module not found: jdk.sctp
error: module not found: jdk.jsobject
error: module not found: jdk.editpad
error: module not found: jdk.jshell
error: module not found: jdk.management.agent
error: module not found: jdk.javadoc
error: module not found: jdk.crypto.ec
error: module not found: jdk.attach
error: module not found: jdk.zipfs
error: module not found: jdk.jconsole
error: module not found: jdk.naming.rmi
error: module not found: jdk.compiler
error: module not found: java.se
error: module not found: jdk.net
error: module not found: jdk.crypto.cryptoki
error: module not found: jdk.jcmd
error: module not found: jdk.httpserver
error: module not found: jdk.jstatd
error: module not found: jdk.jfr
error: module not found: jdk.xml.dom
error: module not found: jdk.hotspot.agent
error: module not found: jdk.charsets
error: module not found: jdk.jdi
error: module not found: jdk.management.jfr
error: module not found: jdk.incubator.vector
Exception in thread "main" java.lang.IllegalStateException: Missing: c:\ojdkbuild\build\openjdk\support\gensrc\*;c:\ojdkbuild\lookaside\java-17-openjdk\src\*\windows\classes;c:\ojdkbuild\lookaside\java-17-openjdk\src\*\share\classes
	at build.tools.symbolgenerator.JavadocElementList.main(JavadocElementList.java:101)

**Comment by ojdkbuild** [comment]
Hi, thanks for the report. There is not enough info to tell what is wrong, can you provide some more details about your environment and CMake flags? I can guess that it may be related to Cygwin.

Note: to build vanilla jdk17 it may be better to use this repo: https://github.com/openjdk/jdk17u

**Comment by ojdkbuild** [comment]
Closing the issue, please reopen if necessary.
