### ISSUE TITLE
Could you provide JRE only build?

### ISSUE THREAD

**Issue by 3oheicrw** [ojdkbuild/ojdkbuild#138]
Alongside with the JDK build, please.

**Comment by ojdkbuild** [comment]
Hi, JRE bundles are available on release pages, they are built for every jdk version:

 - [8u312](https://github.com/ojdkbuild/ojdkbuild/releases/tag/java-1.8.0-openjdk-1.8.0.312-1.b07): java-1.8.0-openjdk-jre-1.8.0.312-1.b07.ojdkbuild.windows.x86_64.zip
 - [11.0.13](https://github.com/ojdkbuild/ojdkbuild/releases/tag/java-11-openjdk-11.0.13.8-1): java-11-openjdk-jre-11.0.13.8-1.windows.ojdkbuild.x86_64.zip and java-11-openjdk-jre-11.0.13.8-1.windows.ojdkbuild.x86_64.msi
 - [17.0.1](https://github.com/ojdkbuild/ojdkbuild/releases/tag/java-17-openjdk-17.0.1.0.12-1): java-17-openjdk-17.0.1.0.12-1.win.x86_64.zip and java-17-openjdk-17.0.1.0.12-1.win.x86_64.msi

Note, there is no separate MSI installer for 8u JRE, instead JRE-only install can be done from the main installer.

**Comment by ojdkbuild** [comment]
Closing the issue.
