### ISSUE TITLE
OpenJDK 8u322-GA Question

### ISSUE THREAD

**Issue by patris70** [ojdkbuild/ojdkbuild#139]
Hallo,

has OpenJDK 8uxxx Source Code new Link for download?
Here is last Update on 8 Week ago and is not GA Version!!
http://hg.openjdk.java.net/jdk8u/jdk8u

Thanks

**Comment by ojdkbuild** [comment]
Hi, latest 8u sources are available in [this repo](https://hg.openjdk.java.net/jdk8u/monojdk8u/), it is an intermediate repo for mercurial->git transition, [some details on it](https://mail.openjdk.java.net/pipermail/jdk8u-dev/2021-October/014344.html). ojdkbuild build of it is expected to be ready later this week (may slip some days to the following week).

**Comment by patris70** [comment]
@ojdkbuild,

Thanks for Info. I have two questions:

1- is b06, GA Version?

2- from where can i download source code of jdk 17?

Thanks

**Comment by ojdkbuild** [comment]
Hi,

> 1- is b06, GA Version?

Yes, 8u322-b06 is GA. 

> 2- from where can i download source code of jdk 17?
 
All openjdk git repos are [here](https://github.com/openjdk), [link to 17 one](https://github.com/openjdk/jdk17u).

Hope this helps

**Comment by patris70** [comment]
Hi,

Thanks very much.
