### ISSUE TITLE
[FR] add IcedTea-Web to builds

### ISSUE THREAD

**Issue by ildar** [ojdkbuild/ojdkbuild#14]
so that users could use javaws *.jnlp

**Comment by ojdkbuild** [comment]
M, writing proper `javaws` wrapper for windows may be not a small task due to various config and caching details. At the same time `netx.jar` from IcedTea-Web can be used directly the following way:

    java -Xbootclasspath/a:netx.jar net.sourceforge.jnlp.runtime.Boot some.jnlp

I am currently not user about ITW on windows and will leave this issue open for now.

**Comment by ildar** [comment]
Dear,
thanks a lot for help. Unfortunately it didn't work.
I took netx.jar from Linux. Error log:

> Z:\>c:\java\bin\java -Xbootclasspath/a:netx.jar
net.sourceforge.jnlp.runtime.Boot webstart_20170330100610.jnlp
> java.net.URISyntaxException: Illegal character in authority at index 7:
file://C:\Documents and
Settings\Administrator\.config\icedtea-web\security\java.policy
>         at java.net.URI$Parser.fail(URI.java:2848)
>         at java.net.URI$Parser.parseAuthority(URI.java:3186)
>         at java.net.URI$Parser.parseHierarchical(URI.java:3097)
>         at java.net.URI$Parser.parse(URI.java:3053)
>         at java.net.URI.<init>(URI.java:588)
>         at
net.sourceforge.jnlp.runtime.JNLPPolicy.getPolicyFromUrl(JNLPPolicy.java:188)

>         at
net.sourceforge.jnlp.runtime.JNLPPolicy.<init>(JNLPPolicy.java:64)
>         at
net.sourceforge.jnlp.runtime.JNLPRuntime.initialize(JNLPRuntime.java:260)
>         at net.sourceforge.jnlp.runtime.Boot.init(Boot.java:326)
>         at net.sourceforge.jnlp.runtime.JnlpBoot.run(JnlpBoot.java:58)
>         at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:245)
>         at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:63)
>         at java.security.AccessController.doPrivileged(Native Method)
>         at net.sourceforge.jnlp.runtime.Boot.main(Boot.java:195)
>
> Removing execute permissions on file C:\Documents and
Settings\Administrator\.config\icedtea-web\security\trusted.clientcerts.temp
failed
> Removing read permission on file C:\Documents and
Settings\Administrator\.config\icedtea-web\security\trusted.clientcerts.temp
failed
> Removing execute permissions on file C:\Documents and
Settings\Administrator\.config\icedtea-web\security\trusted.jssecerts.temp
failed
> Removing read permission on file C:\Documents and
Settings\Administrator\.config\icedtea-web\security\trusted.jssecerts.temp
failed
> Removing execute permissions on file C:\Documents and
Settings\Administrator\.config\icedtea-web\security\trusted.certs.temp
failed
> Removing read permission on file C:\Documents and
Settings\Administrator\.config\icedtea-web\security\trusted.certs.temp
failed
> Removing execute permissions on file C:\Documents and
Settings\Administrator\.config\icedtea-web\security\trusted.jssecacerts.temp
failed
> Removing read permission on file C:\Documents and
Settings\Administrator\.config\icedtea-web\security\trusted.jssecacerts.temp
failed
> Removing execute permissions on file C:\Documents and
Settings\Administrator\.config\icedtea-web\security\trusted.cacerts.temp
failed
> Removing read permission on file C:\Documents and
Settings\Administrator\.config\icedtea-web\security\trusted.cacerts.temp
failed
> Unable to use Firefox's proxy settings. Using "DIRECT" as proxy type.
> Removing execute permissions on file
T:\Administrator\netx\locks\netx_running.temp failed
> Removing read permission on file
T:\Administrator\netx\locks\netx_running.temp failed
> Removing execute permissions on file C:\Documents and
Settings\Administrator\.cache\icedtea-web\cache\recently_used.temp failed
> Removing read permission on file C:\Documents and
Settings\Administrator\.cache\icedtea-web\cache\recently_used.temp failed
> Removing execute permissions on file Z:\C_\Documents and
Settings\Administrator\.cache\icedtea-web\cache\0\https\www-03.ibm.com\services\epadm\epadm.jar.info.temp
failed
> Removing read permission on file Z:\C_\Documents and
Settings\Administrator\.cache\icedtea-web\cache\0\https\www-03.ibm.com\services\epadm\epadm.jar.info.temp
failed
> The application is a local file. Codebase validation is disabled. See:
http://docs.oracle.com/javase/7/docs/technotes/guides/jweb/security/no_redeploy.html
for details.
> The application is a local file. Codebase validation is disabled. See:
http://docs.oracle.com/javase/7/docs/technotes/guides/jweb/security/no_redeploy.html
for details.
> netx: Initialization Error: Could not initialize application. ()
> net.sourceforge.jnlp.LaunchException: Fatal: Initialization Error: Could
not initialize application. The application has not been initialized, for
more information execute javaws from the command line.
>     at net.sourceforge.jnlp.Launcher.createApplication(Launcher.java:813)
>     at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:532)
>     at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:936)
> Caused by: java.lang.NullPointerException
>     at
net.sourceforge.jnlp.security.SecurityDialogs.showMatchingALACAttributePanel(SecurityDialogs.java:405)

>     at
net.sourceforge.jnlp.runtime.ManifestAttributesChecker.checkApplicationLibraryAllowableCodebaseAttribute(ManifestAttributesChecker.java:426)

>     at
net.sourceforge.jnlp.runtime.ManifestAttributesChecker.checkAll(ManifestAttributesChecker.java:122)

>     at
net.sourceforge.jnlp.runtime.JNLPClassLoader.initializeResources(JNLPClassLoader.java:777)

>     at
net.sourceforge.jnlp.runtime.JNLPClassLoader.<init>(JNLPClassLoader.java:285)

>     at
net.sourceforge.jnlp.runtime.JNLPClassLoader.createInstance(JNLPClassLoader.java:357)

>     at
net.sourceforge.jnlp.runtime.JNLPClassLoader.getInstance(JNLPClassLoader.java:429)

>     at
net.sourceforge.jnlp.runtime.JNLPClassLoader.getInstance(JNLPClassLoader.java:403)

>     at net.sourceforge.jnlp.Launcher.createApplication(Launcher.java:805)
>     ... 2 more

**Comment by ojdkbuild** [comment]
You are right, it worked before, but it looks like recent Netx changes broke something about path handling on windows.

**Comment by ojdkbuild** [comment]
I talked with IcedTea-Web devs, this is going to be fixed, but the work probably will start only after the April security release.

**Comment by ildar** [comment]
:) good to hear. No urgency on my side.

**Comment by ojdkbuild** [comment]
IcedTea-Web is integrated into 8u151, see [announce](https://groups.google.com/d/msg/ojdkbuild/7Zd4lJ98M0g/1KgUUcVzAgAJ).

Note, that the version included has minor differences from upstream ITW - additional tools, like Policy Editor are disabled from menu (still can be run manually). Such tools for fine-tuning local config make less sense for included ITW, as its config will be deleted on re-install or update. I can suggest using upstream ITW, if such tools and persistent local config are critical.

**Comment by ildar** [comment]
That's so great, thanks you so much!
Though to use [this beast](
https://www.ibm.com/developerworks/community/wikis/home?lang=en#!/wiki/W5586ee257100_437f_a60d_4f7992097cb9/page/Workstation%20Requirements)
I need 32 bit Java with javaws. I already asked about it in
https://github.com/ojdkbuild/ojdkbuild/issues/2

> --
Ildar Mulyukov,
child of God

email: ildar.mulyukov@gmail.com
GoogleTalk: ildar.mulyukov@gmail.com
blog: http://johan-notes.blogspot.com/

**Comment by ojdkbuild** [comment]
@ildar , currently x86 MSI can be built, and WebStart works fine on it. But it cannot be installed on x86 windows - installer settings require x86_64 windows. And installer is needed for WebStart to set proper registry keys to register JNLP extension. I have no plans to support x86 windows in MSI.

I think MSI config can be adjusted to run on x86 windows, if you'd like to continue with it yourself - I can provide more details how to do so.

**Comment by ildar** [comment]
Actually I indeed need 32 bit jre on 64 bit system 🙂
But frankly I'm concerned what confusion'll happen if you push this version
out.

**Comment by ojdkbuild** [comment]
@ildar , the following worked for me to build x86 MSI that can be used on x86_64 windows:

    git clone --recursive https://github.com/ojdkbuild/ojdkbuild.git
    cd ojdkbuild
    resources\scripts\set-compile-env-vs10-x86.bat
    mkdir build
    cd build
    cmake ../src/java-1.8.0-openjdk -Dopenjdk_32_BIT=ON
    nmake installer

I do not want to publish such binaries myself to not confuse users, who would expect x86 MSI to run on x86 Windows.

**Comment by ildar** [comment]
Right.
Then i would hardly ever get the MSI as I don't have any plan to deploy M$
toolkits 🙁
If you built it already could you please drop it to a cloud somewhere away
from users? Just once?

**Comment by ojdkbuild** [comment]
@ildar uploaded x86 MSI here - https://drive.google.com/open?id=1cmVvtHWN5lx_ydJ52HXMLMSDKJqdTsAx

**Comment by ildar** [comment]
Big great THANKS a lot!
I'll pick it up tomorrow.
