### ISSUE TITLE
深入理解java虚拟机第三版有问

### ISSUE THREAD

**Issue by Curllen** [ojdkbuild/ojdkbuild#140]
书中附件地址:  [[2]](https://github.com/ojdkbuild/ojdkbuild/Text/Chapter-30.xhtml#link-1) https://github.com/ojdkbuild/ojdkbuild/blob/master/src/java-12-openjdk/CMakeLists.txt

但是这个文件不存在

**Comment by clsnull** [comment]
可以看一下history, https://github.com/ojdkbuild/ojdkbuild/blob/0a8762394f4f7f7052adf29a7d43f61aacb1047d/src/java-12-openjdk/CMakeLists.txt
