### ISSUE TITLE
ojdkbuild OpenJDK Latest Version?

### ISSUE THREAD

**Issue by PowerUser1234** [ojdkbuild/ojdkbuild#141]
I notice that the multiplatform free downloads of the Microsoft Java OpenJDK seem to go up to version 17.

Will there be a version 18, or later? Does 17 include the Modules system, and their ability to shut down the reflection mechanism?

**Comment by ojdkbuild** [comment]
Sorry, this whole project is discontinued, I can suggest to look for OpenJDK builds [from some other vendor](https://en.wikipedia.org/wiki/OpenJDK#OpenJDK_builds).
