### ISSUE TITLE
Where the build project under openjdk offical organize?

### ISSUE THREAD

**Issue by hh23485** [ojdkbuild/ojdkbuild#145]
Where the build project link under openjdk offical organize?
The same name `objdbuild` is not in openjdk, and no release found there.

**Comment by hh23485** [comment]
I mean, After deprecated this proj, where is the best way to find the release of JDK?

**Comment by 3oheicrw** [comment]
I wondered the same. I'm using Windows 7 and don't know if there is other JDK builds that still works on my system. They seem all increased the requirement to at least Windows 8.1 (Windows Server 2012r2). He suddenly deprecated the project, pointing us to the openjdk project's github with a bunch of repos but didn't tell us where to get the binaries.

**Comment by ojdkbuild** [comment]
Sorry, this whole project is discontinued, I can suggest to look for OpenJDK builds [from some other vendor](https://en.wikipedia.org/wiki/OpenJDK#OpenJDK_builds).
