### ISSUE TITLE
how to build experimental JDK flavors using this toolchain?

### ISSUE THREAD

**Issue by wizzard0** [ojdkbuild/ojdkbuild#15]
Prerequisite: I can successfully build vanilla JDK8.1.121x64 with this toolchain on Win10x64 VM.

I want to build the JDK9 Shenandoah GC branch, like this: https://wiki.openjdk.java.net/display/shenandoah/Main

But I'm a bit puzzled as of where to start tweaking it to checkout and build the correct one. Where do I start?

**Comment by ojdkbuild** [comment]
Hi, as these builds are targeted to produce "shippable" jdks, I would recommend to build Shenandoah with jdk8 (jdk9 is yet pre-release and not fully supported). Build steps for jdk8:

On linux:

    curl -LO http://pkgs.fedoraproject.org/cgit/rpms/java-1.8.0-openjdk.git/plain/generate_source_tarball.sh
    PROJECT_NAME=aarch64-port REPO_NAME=jdk8u-shenandoah VERSION=aarch64-shenandoah-jdk8u121-b14-shenandoah-merge-2017-03-23 bash ./generate_source_tarball.sh

That will give you a tarball with an overly long name `aarch64-port-jdk8u-shenandoah-aarch64-shenandoah-jdk8u121-b14-shenandoah-merge-2017-03-23.tar.xz`. Move it to windows and unpack it, there - it will give `openjdk` dir. On windows:

    cd ojdkbuild
    cd lookaside
    cd java-1.8.0-openjdk
    git checkout lookaside
    git branch tmp-shenandoah-lookaside
    git checkout tmp-shenandoah-lookaside
    git rm -rf *
    # now move all the files from unpacked tarball above into `ojdkbuild/lookaside/java-1.8.0-openjdk`, that is now empty
    git add *
    git status 
    # check that shenandoah*.cpp sources are in the above list
    git commit -am "import aarch64-port-jdk8u-shenandoah-aarch64-shenandoah-jdk8u121-b14-shenandoah-merge-2017-03-23"
    git checkout master
    git branch tmp-shenandoah-master
    git checkout tmp-shenandoah-master
    git merge tmp-shenandoah-lookaside
    # currently the merge above is clean, it may require some manual merging depending on tarball revision
    cd ..\..
    # we are in ojdkbuild root now
    resources\scripts\set-compile-env-vs10-x86_64.bat
    rd /s /q build
    mkdir build
    cd build
    cmake ../src/java-1.8.0-openjdk
    nmake zip

This will give you jdk8 binaries with up-to-date Shenandoah, at least `java -XX:+UseShenandoahGC -version` worked for me.

**Comment by ojdkbuild** [comment]
Closing this, please reopen if mode details on Shenandoah needed.

**Comment by ojdkbuild** [comment]
Note, Shenandoah GC added to jdk8 in 8u151 build - https://groups.google.com/forum/#!msg/ojdkbuild/7Zd4lJ98M0g/1KgUUcVzAgAJ
