### ISSUE TITLE
Compact Profile

### ISSUE THREAD

**Issue by ui4j** [ojdkbuild/ojdkbuild#16]
I want to build compact profile instead of full JRE.
How could i customize the build process for Windows environment?

**Comment by ojdkbuild** [comment]
Hi, assuming you are talking about jdk8, can you give a link to what you mean will be a "compact profile" on windows? I admittedly haven't looked into compact for a long time (so may confuse "profile" here with something else), but always was under the impression that it is linux-only thing.

If this is about jdk9 and modules - it is not released yet and not "fully supported". I'd like to wait for the "dust to settle" around modules (no more changes to modules impl, best practices for modules build on linux etc) before touching anything there.

**Comment by ui4j** [comment]
[Compact Profiles](http://www.oracle.com/technetwork/java/embedded/resources/tech/compact-profiles-overview-2157132.html) is subset of Java SE Api which does not contain Swing, Corba, RMI etc. There are three types of compact profile; compact1, compact2, and compact3. Each profile includes the APIs of the lower-numbered profiles (compact2 is a superset of compact1). Additionally compact profiles are smaller then full JRE.

--

I could build compact profiles with `make profiles` command.

This command build JRE & JDK:
```bash
    make images \
        JAVAC_FLAGS=-g \
        LOG=${${PROJECT_NAME}_LOG_LEVEL} \
        2>&1
```

[This command](https://github.com/ojdkbuild/ojdkbuild/blob/master/src/java-1.8.0-openjdk/resources/configure-and-make.sh#L46) build JRE, JDK and compact profiles:
```bash
    make images \
        JAVAC_FLAGS=-g \
        LOG=${${PROJECT_NAME}_LOG_LEVEL} \
        2>&1
    make profiles \
        JAVAC_FLAGS=-g \
        LOG=${${PROJECT_NAME}_LOG_LEVEL} \
        2>&1
```

Thanks

**Comment by ojdkbuild** [comment]
Thanks, this info is useful. Though I don't want to add profiles builds as separate downloads in ojdkbuild releases (there are too many release artifacts already). I will close this issue and will point possible future questions about profiles to it.

**Comment by ojdkbuild** [comment]
Just for the record, compact profiles are [getting removed from jdk11](http://mail.openjdk.java.net/pipermail/build-dev/2018-April/021900.html).
