### ISSUE TITLE
macOS?

### ISSUE THREAD

**Issue by njlr** [ojdkbuild/ojdkbuild#17]
I was referred to this project from https://github.com/alexkasko/openjdk-unofficial-builds, which is now deprecated. I am looking for a Java 8 bundle for macOS. 

Does ojdkbuild provide this?

**Comment by ojdkbuild** [comment]
Hi, no, there are no Mac builds in this projects, some details on it are in [this thread](https://github.com/ojdkbuild/ojdkbuild/issues/1#issuecomment-222149740). Shortly, mac-jdk8 is easy to build, but very hard to maintain after Oracle ends public updates for jdk8.

Closing as "wontfix".

**Comment by njlr** [comment]
For the lazy, I have put my JRE here: https://github.com/njlr/ojdk/releases
