### ISSUE TITLE
Add Linux 32 bits support

### ISSUE THREAD

**Issue by rarguello** [ojdkbuild/ojdkbuild#19]
# Introduction
I needed a 32 bit Linux version (don't ask) so I repeated the "CentOS6ZipBundle" procedure to create the 32 bits openjdk zip. These are the steps I followed, it's almost the same procedure, but some paths have to be changed.

Note that there isn't a Docker image for a 32 bits CentOS 6, so you need to use virtualization (KVM or VirtualBox) to install a minimal CentOS 6.9 image (CentOS-6.9-i386-minimal.iso).

# Goal
Bundle java-1.8.0-openjdk binary package from CentOS 6 as a "relatively portable" ZIP bundle.

# Prerequisites
Linux x86_64 machine that can run KVM or VirtualBox.

# Process
Download the 32 bits minimal install ISO from a CentOS mirror, and install a virtual machine with CentOS 6.

Login into it and install required packages:

```
yum update -y
yum install zip yum-utils -y
adduser jdk
su - jdk
```

Under normal user, download `java-1.8.0-openjdk` binary packages and some dependencies:

```
mkdir tmp
cd tmp
yumdownloader java-1.8.0-openjdk java-1.8.0-openjdk-headless java-1.8.0-openjdk-devel java-1.8.0-openjdk-src ca-certificates tzdata-java dejavu-sans-fonts dejavu-sans-mono-fonts dejavu-serif-fonts
for fi in `ls *.rpm` ; do rpm2cpio $fi | cpio -idmv ; done
```

Add timezone data, CA certificates file and fonts:

```
rm ./usr/lib/jvm/java-1.8.0-openjdk.i386/jre/lib/tzdb.dat
cp -p ./usr/share/javazi-1.8/tzdb.dat ./usr/lib/jvm/java-1.8.0-openjdk.i386/jre/lib/
rm ./usr/lib/jvm/java-1.8.0-openjdk.i386/jre/lib/security/cacerts
cp -p ./etc/pki/java/cacerts ./usr/lib/jvm/java-1.8.0-openjdk.i386/jre/lib/security/
cp -pr ./usr/share/fonts/dejavu/ ./usr/lib/jvm/java-1.8.0-openjdk.i386/jre/lib/fonts/
```

Rename library for SunEC security provider effectively disabling it (it may fail outside of CentOS, see [details](http://icedtea.classpath.org/bugzilla/show_bug.cgi?id=2934)):

```
mv ./usr/lib/jvm/java-1.8.0-openjdk.i386/jre/lib/i386/libsunec.so ./usr/lib/jvm/java-1.8.0-openjdk.i386/jre/lib/i386/libsunec.so_DISABLED
```

Bundle image (replace `<version>`):

```
mv ./usr/lib/jvm/java-1.8.0-openjdk-<version>.i386/ .
zip -qr9 java-1.8.0-openjdk-<version>.i386.zip java-1.8.0-openjdk-<version>.i386
```

I uploaded the resulting ZIP to this URL:
[java-1.8.0-openjdk-1.8.0.144-0.b01.el6_9.i386.zip](https://dl.bintray.com/openjdk/openjdk-linux-x86/java-1.8.0-openjdk-1.8.0.144-0.b01.el6_9.i386.zip)

Please include this 32 bit version in your packages!

**Comment by rarguello** [comment]
Yo don't really need a CentOS 32-bits VM to build this. You can run this script from a CentOS/Fedora x86_64 and it will build a OpenJDK 32-bits ZIP:

```
#!/bin/bash

set -e
set -u

openjdk_version="1.8.0.144-0.b01.el6_9"

mkdir tmp
pushd tmp

# Download OpenJDK RPMs
wget http://mirror.centos.org/centos-6/6.9/updates/i386/Packages/java-1.8.0-openjdk-${openjdk_version}.i686.rpm
wget http://mirror.centos.org/centos-6/6.9/updates/i386/Packages/java-1.8.0-openjdk-devel-${openjdk_version}.i686.rpm
wget http://mirror.centos.org/centos-6/6.9/updates/i386/Packages/java-1.8.0-openjdk-headless-${openjdk_version}.i686.rpm
wget http://mirror.centos.org/centos-6/6.9/updates/i386/Packages/java-1.8.0-openjdk-src-${openjdk_version}.i686.rpm

# Download dependencies
wget http://mirror.centos.org/centos-6/6.9/updates/i386/Packages/ca-certificates-2017.2.14-65.0.1.el6_9.noarch.rpm
wget http://mirror.centos.org/centos-6/6.9/os/i386/Packages/dejavu-sans-fonts-2.33-1.el6.noarch.rpm
wget http://mirror.centos.org/centos-6/6.9/os/i386/Packages/dejavu-sans-mono-fonts-2.33-1.el6.noarch.rpm
wget http://mirror.centos.org/centos-6/6.9/os/i386/Packages/dejavu-serif-fonts-2.33-1.el6.noarch.rpm
wget http://mirror.centos.org/centos-6/6.9/updates/i386/Packages/tzdata-java-2017b-1.el6.noarch.rpm

for rpm in `ls *.rpm`
  do rpm2cpio $rpm | cpio -idm;
done

rm ./usr/lib/jvm/java-1.8.0-openjdk.i386/jre/lib/tzdb.dat
cp -p ./usr/share/javazi-1.8/tzdb.dat ./usr/lib/jvm/java-1.8.0-openjdk.i386/jre/lib/
rm ./usr/lib/jvm/java-1.8.0-openjdk.i386/jre/lib/security/cacerts
cp -p ./etc/pki/java/cacerts ./usr/lib/jvm/java-1.8.0-openjdk.i386/jre/lib/security/
cp -pr ./usr/share/fonts/dejavu/ ./usr/lib/jvm/java-1.8.0-openjdk.i386/jre/lib/fonts/
mv ./usr/lib/jvm/java-1.8.0-openjdk.i386/jre/lib/i386/libsunec.so ./usr/lib/jvm/java-1.8.0-openjdk.i386/jre/lib/i386/libsunec.so_DISABLED

mv ./usr/lib/jvm/java-1.8.0-openjdk-${openjdk_version}.i386/ .
zip -qr9 java-1.8.0-openjdk-${openjdk_version}.i386.zip java-1.8.0-openjdk-${openjdk_version}.i386
mv java-1.8.0-openjdk-${openjdk_version}.i386.zip ../

popd
```

**Comment by ojdkbuild** [comment]
Hi, can recommend against using i386 builds from CentOS. CentOS version of jdk introduces more system dependencies, than upstream one.  That works well when such jdk is installed from package manager (with all deps installed automatically). But if you want a "semi-portable" bundle, these additional dependencies can cause problems.  Even x86_64 version (discussion #1 ) can be problematic to run on other machines because of these deps. For i386 version situation is worse, as you need i386 dependent libs, that may be harder to setup on x86_64 linux.

It may be more convenient to build i386 version on linux directly from upstream sources instead.
