### ISSUE TITLE
Add Windows 32bits build

### ISSUE THREAD

**Issue by anthony-o** [ojdkbuild/ojdkbuild#2]
Could it be possible to add a build targeting Windows 32 bits?

**Comment by ojdkbuild** [comment]
Hi, all the groundwork for 32-bit builds is there - openjdk supports x86 builds on x86_64 windows host and all the dependencies are built with cmake so their compilation config can be changed easily. I never tried it yet so some changes to build system most probably will be required. Currently there is no ETA for 32-bit windows builds. I want to look into them after the 8u101 release in July. Also a link to maillist just for the reference - https://groups.google.com/forum/#!topic/ojdkbuild/e18am6GMV8U

**Comment by robinpaulson** [comment]
Hi, I'd be keen to see win 32 builds as well, any news on this?

Cheers

**Comment by ojdkbuild** [comment]
Hi, no news on 32 bit builds yet, but they are still planned. I will probably look into them after the 8u111 release in October.

**Comment by bome** [comment]
I have a fork with a 32-bit build. It works, but it disables 64-bit build.
https://github.com/bome/ojdkbuild

**Comment by ojdkbuild** [comment]
Thanks for the link! I will take these changes into account for 32-bit work.

**Comment by JohnMurga** [comment]
Thank you so much for the ARM32 builds which I am trying now :-)
How likely is it that we'll see Win32 builds ?

**Comment by ojdkbuild** [comment]
@JohnMurga , that's nice to have some users for AArch32 builds! Still no ETA for Win32, but it is still planned. I need to deal with debug symbols (#7) first.

**Comment by jbrueggmann** [comment]
Hello everybody, is there any update on the Win32 build? I've tried building one myself through the fork of @bome but I failed miserably :)

**Comment by ojdkbuild** [comment]
@jbrueggmann , yes, some dependencies (especially libjpeg-turbo, that is mostly ASM) need a cleanup to support 32-bit builds. I'd like to do that but cannot promise exact ETA.

**Comment by reke592** [comment]
Hi sir, is there any update on the Win32 build? Thanks

**Comment by ojdkbuild** [comment]
@reke592 , I have all dep libraries built for win32, now need to integrate that in the build process. There going to be a security release 8u121 in a week or two. If everything will go okay, in some weeks after that I am going to do a "feature" release that will include 32-bit. Only ZIP-bundle is planned for 32-bit build, there will be no 32-bit MSI (at least not in the initial version).

**Comment by ojdkbuild** [comment]
Added support for x86 builds (`openjdk_32_BIT` flag) and built binaries for 8u121 - https://groups.google.com/d/msg/ojdkbuild/I_sKh2X1S-s/aThQVcr7AQAJ

Closing the issue.

**Comment by JohnMurga** [comment]
Awesome, testing shortly

**Comment by TheFutureStartsNow** [comment]
Hi, can you also describe where to set this flag or how to build 32 bit zip on my own?
Thanks!

**Comment by ojdkbuild** [comment]
@TheFutureStartsNow , yep, something like this should work (assuming clean win2012):

    git clone https://github.com/ojdkbuild/ojdkbuild.git
    cd ojdkbuild
    "resources/scripts/modules.bat" resources/profiles/jdk8_zip.gitmodules.txt
    call "resources/scripts/set-compile-env-vs10-x86.bat"
    mkdir build
    cd build
    cmake ../src/java-1.8.0-openjdk -Dopenjdk_32_BIT=ON -G "NMake Makefiles"
    nmake zip

On success zip bundle will be placed into `ojdkbuild/dist` directory.

**Comment by ildar** [comment]
This port is 👍.
But is it possible to also add the installer? I desire IceTeeWeb in it: https://github.com/ojdkbuild/ojdkbuild/issues/14#event-1321747508
Thanks in advance!
