### ISSUE TITLE
java-1.8.0-openjdk-1.8.0.151-1.b12.ojdkbuild.windows.x86: net.dll file is deleted

### ISSUE THREAD

**Issue by psramka** [ojdkbuild/ojdkbuild#21]
Steps to reproduce:
1) Install java-1.8.0-openjdk-1.8.0.151-1.b12.ojdkbuild.windows.x86.
2) Go to directory jre\bin and notice that there are 64 items, one of which is the file net.dll.
3) Use maven to do a build (of any random project): mvn clean install
4) Notice that maven ends with this message: Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\java-1.8.0-openjdk-1.8.0.151-1.b12.ojdkbuild.windows.x86\jre\bin\net.dll: Access is denied
5) Go to directory jre\bin and notice that there are now 63 items and the file net.dll has been deleted.
Attached is the complete output from the mvn clean install.

[out.txt](https://github.com/ojdkbuild/ojdkbuild/files/1448211/out.txt)

**Comment by ojdkbuild** [comment]
Hi, I just tried this build locally and cannot reproduce this. After building maven project I still can see 64 files on `jre\bin`.

Could you please try [FileMon](https://docs.microsoft.com/en-us/sysinternals/downloads/filemon) to find out which process deletes `net.dll` for you?

**Comment by psramka** [comment]
Thank you for getting back to me so quickly.

I can no longer reproduce the problem. Please close this Issue. I apologize
for any inconvenience

Thank you,
Peter Sramka

"The true sign of intelligence is not knowledge but imagination." -- Albert
Einstein

**Comment by psramka** [comment]
This problem has resurfaced. I have opened a new Issue to address this: #22
