### ISSUE TITLE
java-1.8.0-openjdk-1.8.0.151-1.b12.ojdkbuild.windows.x86: net.dll file is deleted (Reopened)

### ISSUE THREAD

**Issue by psramka** [ojdkbuild/ojdkbuild#22]
Please reference #21 for background information. As it turns out, this problem has resurfaced again. Apparently, this problem is intermittent. Please find attached output from Process Monitor that demonstrates the problem. If you need any other debugging information from me, please feel free to ask.

[Logfile.txt](https://github.com/ojdkbuild/ojdkbuild/files/1452092/Logfile.txt)

**Comment by ojdkbuild** [comment]
Hi, looking on the relevant bits below extracted from the log file, I cannot see any obvious reasons why the file was deleted. If you find a way to reproduce this problem reliably - please update the issue.

      <Time_of_Day>6:33:21.5550663 PM</Time_of_Day>
      <Process_Name>java.exe</Process_Name>
      <PID>1020</PID>
      <Operation>CreateFile</Operation>
      <Path>C:\java-1.8.0-openjdk-1.8.0.151-1.b12.ojdkbuild.windows.x86\jre\bin\net.dll</Path>
      <Result>SUCCESS</Result>
      <Detail>Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a,
        ShareMode: Read, Write, Delete, AllocationSize: n/a, OpenResult: Opened</Detail>

      <Time_of_Day>6:33:21.5551211 PM</Time_of_Day>
      <Process_Name>java.exe</Process_Name>
      <PID>1020</PID>
      <Operation>QueryNetworkOpenInformationFile</Operation>
      <Path>C:\java-1.8.0-openjdk-1.8.0.151-1.b12.ojdkbuild.windows.x86\jre\bin\net.dll</Path>
      <Result>SUCCESS</Result>
      <Detail>CreationTime: 11/1/2017 11:19:52 AM, LastAccessTime: 11/1/2017 11:19:52 AM, LastWriteTime: 11/7/2017
        6:31:44 PM, ChangeTime: 11/7/2017 6:31:44 PM, AllocationSize: 77824, EndOfFile: 74752, FileAttributes: A
      </Detail>

      <Time_of_Day>6:33:21.5551455 PM</Time_of_Day>
      <Process_Name>java.exe</Process_Name>
      <PID>1020</PID>
      <Operation>CloseFile</Operation>
      <Path>C:\java-1.8.0-openjdk-1.8.0.151-1.b12.ojdkbuild.windows.x86\jre\bin\net.dll</Path>
      <Result>SUCCESS</Result>
      <Detail></Detail>

      <Time_of_Day>6:33:21.5555872 PM</Time_of_Day>
      <Process_Name>java.exe</Process_Name>
      <PID>1020</PID>
      <Operation>CreateFile</Operation>
      <Path>C:\java-1.8.0-openjdk-1.8.0.151-1.b12.ojdkbuild.windows.x86\jre\bin\net.dll</Path>
      <Result>SUCCESS</Result>
      <Detail>Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a,
        ShareMode: Read, Write, Delete, AllocationSize: n/a, OpenResult: Opened</Detail>

      <Time_of_Day>6:33:21.5556292 PM</Time_of_Day>
      <Process_Name>java.exe</Process_Name>
      <PID>1020</PID>
      <Operation>QueryBasicInformationFile</Operation>
      <Path>C:\java-1.8.0-openjdk-1.8.0.151-1.b12.ojdkbuild.windows.x86\jre\bin\net.dll</Path>
      <Result>SUCCESS</Result>
      <Detail>CreationTime: 11/1/2017 11:19:52 AM, LastAccessTime: 11/1/2017 11:19:52 AM, LastWriteTime: 11/7/2017
        6:31:44 PM, ChangeTime: 11/7/2017 6:31:44 PM, FileAttributes: A</Detail>

      <Time_of_Day>6:33:21.5556523 PM</Time_of_Day>
      <Process_Name>java.exe</Process_Name>
      <PID>1020</PID>
      <Operation>CloseFile</Operation>
      <Path>C:\java-1.8.0-openjdk-1.8.0.151-1.b12.ojdkbuild.windows.x86\jre\bin\net.dll</Path>
      <Result>SUCCESS</Result>
      <Detail></Detail>

      <Time_of_Day>6:33:21.5557443 PM</Time_of_Day>
      <Process_Name>java.exe</Process_Name>
      <PID>1020</PID>
      <Operation>CreateFile</Operation>
      <Path>C:\java-1.8.0-openjdk-1.8.0.151-1.b12.ojdkbuild.windows.x86\jre\bin\net.dll</Path>
      <Result>SUCCESS</Result>
      <Detail>Desired Access: Read Data/List Directory, Execute/Traverse, Synchronize, Disposition: Open, Options:
        Synchronous IO Non-Alert, Non-Directory File, Attributes: n/a, ShareMode: Read, Delete, AllocationSize: n/a,
        OpenResult: Opened</Detail>

      <ProcessIndex>112</ProcessIndex>
      <Time_of_Day>6:33:21.5557936 PM</Time_of_Day>
      <Process_Name>java.exe</Process_Name>
      <PID>1020</PID>
      <Operation>CreateFileMapping</Operation>
      <Path>C:\java-1.8.0-openjdk-1.8.0.151-1.b12.ojdkbuild.windows.x86\jre\bin\net.dll</Path>
      <Result>ACCESS DENIED</Result>
      <Detail>SyncType: SyncTypeCreateSection, PageProtection: </Detail>

      <Time_of_Day>6:33:21.6515550 PM</Time_of_Day>
      <Process_Name>java.exe</Process_Name>
      <PID>1020</PID>
      <Operation>CloseFile</Operation>
      <Path>C:\java-1.8.0-openjdk-1.8.0.151-1.b12.ojdkbuild.windows.x86\jre\bin\net.dll</Path>
      <Result>SUCCESS</Result>
      <Detail></Detail>

      <Time_of_Day>6:33:21.6518953 PM</Time_of_Day>
      <Process_Name>java.exe</Process_Name>
      <PID>1020</PID>
      <Operation>CreateFile</Operation>
      <Path>C:\java-1.8.0-openjdk-1.8.0.151-1.b12.ojdkbuild.windows.x86\jre\bin\net.dll</Path>
      <Result>NAME NOT FOUND</Result>
      <Detail>Desired Access: Generic Read, Disposition: Open, Options: Synchronous IO Non-Alert, Non-Directory File,
        Attributes: N, ShareMode: Read, Write, AllocationSize: n/a</Detail>

      <Time_of_Day>6:33:22.6353397 PM</Time_of_Day>
      <Process_Name>Explorer.EXE</Process_Name>
      <PID>2720</PID>
      <Operation>QueryDirectory</Operation>
      <Path>C:\java-1.8.0-openjdk-1.8.0.151-1.b12.ojdkbuild.windows.x86\jre\bin\net.dll</Path>
      <Result>NO SUCH FILE</Result>
      <Detail>Filter: net.dll</Detail>

      <Time_of_Day>6:33:22.6355268 PM</Time_of_Day>
      <Process_Name>Explorer.EXE</Process_Name>
      <PID>2720</PID>
      <Operation>CreateFile</Operation>
      <Path>C:\java-1.8.0-openjdk-1.8.0.151-1.b12.ojdkbuild.windows.x86\jre\bin\net.dll</Path>
      <Result>NAME NOT FOUND</Result>
      <Detail>Desired Access: Read Attributes, Synchronize, Disposition: Open, Options: Synchronous IO Non-Alert,
        Attributes: N, ShareMode: Read, Write, Delete, AllocationSize: n/a</Detail>

      <Time_of_Day>6:33:22.6359394 PM</Time_of_Day>
      <Process_Name>Explorer.EXE</Process_Name>
      <PID>2720</PID>
      <Operation>QueryDirectory</Operation>
      <Path>C:\java-1.8.0-openjdk-1.8.0.151-1.b12.ojdkbuild.windows.x86\jre\bin\net.dll</Path>
      <Result>NO SUCH FILE</Result>
      <Detail>Filter: net.dll</Detail>

      <Time_of_Day>6:33:22.6361106 PM</Time_of_Day>
      <Process_Name>Explorer.EXE</Process_Name>
      <PID>2720</PID>
      <Operation>CreateFile</Operation>
      <Path>C:\java-1.8.0-openjdk-1.8.0.151-1.b12.ojdkbuild.windows.x86\jre\bin\net.dll</Path>
      <Result>NAME NOT FOUND</Result>
      <Detail>Desired Access: Read Attributes, Synchronize, Disposition: Open, Options: Synchronous IO Non-Alert,
        Attributes: N, ShareMode: Read, Write, Delete, AllocationSize: n/a</Detail>

**Comment by psramka** [comment]
I have been using java-1.8.0-openjdk-1.8.0.151-1.b12.ojdkbuild.windows.x86 for over two months now and the problem has not resurfaced. Therefore, I am closing this issue.
