### ISSUE TITLE
32bit build instructions

### ISSUE THREAD

**Issue by daudo** [ojdkbuild/ojdkbuild#27]
regarding my rejected pull request #26 for a dedicated batchjob for 32bit builds, may I suggest that at least the documentation is updated a little bit?

Right now, you have to search the closed issues to find instructions on how to invoke a 32bit build.

Would be very nice to see at least some kind of instructions either in the README or in the Wiki.
Thanks.

**Comment by ojdkbuild** [comment]
Yes, currently it is a bit obscure, one needs to look [inside the build-all.bat](https://github.com/ojdkbuild/ojdkbuild/blob/0618cd0cd263c49d5fd1994081955bfd069f733c/resources/scripts/build-all.bat#L66) to find out about 32-bit.

I think github doesn't support PR's to [wiki](https://github.com/ojdkbuild/ojdkbuild/wiki) repo. If you'd like to contribute 32-bit instructions - you can write them as a comment to this issue. I'll copy-paste them to a wiki page and link that page from a readme.

**Comment by daudo** [comment]
tried to create a PR for the wiki, but somehow I'm not sure if I really produced a PR or if it just vanished into the nothingness :)

So in order to be sure that you get at least something, here's the link to the wiki page I've created in my fork https://github.com/daudo/ojdkbuild/wiki/32bitBuilds

**Comment by ojdkbuild** [comment]
That's a nice write up, and no PR appeared for wiki (I guess not supported by github). Also I haven't realized, that the whole wiki is included with the forked repo. If you won't mind - I can just link that page (the one inside your fork) from the main readme?

**Comment by daudo** [comment]
no, it isn't included per default, but you can fork git by just appending .wiki to the project name, ie
https://github.com/ojdkbuild/ojdkbuild.wiki.git

For the rest, about linking the wiki page, sure, please do as you wish :)

**Comment by ojdkbuild** [comment]
Added the link to readme, closing the issue
