### ISSUE TITLE
some plan to make el7 version jdk?

### ISSUE THREAD

**Issue by 402309718** [ojdkbuild/ojdkbuild#28]

**Comment by ojdkbuild** [comment]
Hi! Can you be slightly more specific with this question? Do you mean the [jdk linux bundle](https://github.com/ojdkbuild/ojdkbuild/issues/1) from CentOS 7 instead of CentOS 6? jdk is ususally exactly the same in CentOS 6 and 7, just the version built on 6 should be a bit more "portable".

**Comment by ojdkbuild** [comment]
Closing this, please feel free to re-open with more info.
