### ISSUE TITLE
JRE packages

### ISSUE THREAD

**Issue by daudo** [ojdkbuild/ojdkbuild#29]
I've patched the build process to optionally also produce JRE packages.
Are you interested in a PR?

**Comment by ojdkbuild** [comment]
Hi, sorry, I do not want to add separate JRE downloads (they were considered int the past). The number of artifacts for each release is already over the top (and keeps growing - openjfx-10, openjfx-debug and 32-bit MSIs are pending). I understand that JREs may be useful, but currently it should not be that hard to obtain one stripping the parts from JDK ZIP bundle.

**Comment by daudo** [comment]
ok, sure.

But you noticed I mentioned the JREs were **optional** build targets, so no change to the default number of artifacts?

**Comment by ojdkbuild** [comment]
I think such "optional" targets (that are not built during mainline use) have a good chance to become broken over time and still need to be maintained. So I'd rather avoid having them.

**Comment by GitMensch** [comment]
As I've just stumbled over both this issue and [Oracle's notes on the OpenJDK builds they provide][1] I wanted to drop this here:

> Oracle will no longer offer a stand-alone JRE for desktops. Starting with JDK 11 Oracle will only produce a JDK and a Server JRE.

@daudo Was your request for JRE mainly because of final size / built-time needed or did you have other reasons? In general I think a rejected PR will never harm as it saves the work if others want to provide a JRE (and you have a nearly indefinite backup on GitHub of your changes) and is more explicit than a separate repository.
In general: What do you think about the "striping" approach instead of the building change?

[1]:http://jdk.java.net/11/

**Comment by daudo** [comment]
build-time does will not change, because the JRE is just a "side product" of the JDK build. So you'll always have to create the JDK first and then extract the JRE out of it.

My motivation was the final size, there are (many) scenarios where you don't want a fully fledged JDK, ie on embedded devices with very limited amount of storage, not to speak about updating it later on on limited bandwidths.

**Comment by GitMensch** [comment]
@daudo I'd check the PR for the detail, was the optional target actually a striped-off JDK built earlier? What actual commands did you use for striping (and possible re-packaging)?
A PR says more than thousand words ;-)

**Comment by ojdkbuild** [comment]
@daudo , I agree with the concerns about size, just really don't want to add neither more artifacts (that are already too numerous) nor the build logic that is not used.

@GitMensch , Taking `jre` dir from jdk8 ZIP (and re-uploading it somewhere) should work fine.

For jdk11 - a recent relevant discussion: http://mail.openjdk.java.net/pipermail/jdk-dev/2018-July/001546.html

**Comment by daudo** [comment]
@ojdkbuild yes, I understand your concern very well

@GitMensch this commit from my forked repository should explain what I did:
https://github.com/daudo/ojdkbuild/commit/36136edd93a9a969fc8caefcad356eea5e5491a3

**Comment by ojdkbuild** [comment]
Re-opening the issue:

Separate JRE ZIP artifacts were added to jdk8. There is also a support for JRE-only install in installer, see [updated installer features](https://github.com/ojdkbuild/ojdkbuild/wiki/InstallerFeatures#openjdk-8-installation-features).

This is going to be included into upcoming 8u222 release.

There is currently no plans to support JRE artifacts/install options in jdk11+.

**Comment by ojdkbuild** [comment]
8u222 build with JRE option is [available](https://github.com/ojdkbuild/ojdkbuild/releases/tag/java-1.8.0-openjdk-1.8.0.222-1.b10).

**Comment by ojdkbuild** [comment]
Closing this as "done" for jdk8.

Curiously, the supposedly removed from jdk9+ JRE bundles were recently [reintroduced back](http://mail.openjdk.java.net/pipermail/build-dev/2019-March/025241.html). It is currently not clear whether JRE may be useful for jdk11+ so currently there is no plans to add it to 11 installer.
