### ISSUE TITLE
Can't build openjdk

### ISSUE THREAD

**Issue by izhscorp** [ojdkbuild/ojdkbuild#3]
Hi!

I can't build openjdk by ojdkbuild package. See logs in attached files.
[ojdkbuild-logs-20160701.zip](https://github.com/ojdkbuild/ojdkbuild/files/343533/ojdkbuild-logs-20160701.zip)

**Comment by ojdkbuild** [comment]
Replied to this question in a maillist: https://groups.google.com/d/msg/ojdkbuild/7v28eaWZsCY/YopC25niBQAJ

**Comment by ojdkbuild** [comment]
Closing the issue, please re-open if problem persists on clean windows.
