### ISSUE TITLE
Java 10

### ISSUE THREAD

**Issue by quijote** [ojdkbuild/ojdkbuild#31]
Are there any plans to provide a pre-release Windows build of Java 10 with debug symbols here?

**Comment by ojdkbuild** [comment]
Hi, no, current plan is to publish jdk10 binaries only after April update.

Currently jdk10 can be built with ojdkbuild, but it is effectively an upstream build. I suggest building directly from upstream sources instead.

**Comment by marcomsousa** [comment]
JDK10 GA was release today:
http://jdk.java.net/10/

**Comment by ojdkbuild** [comment]
Yep, that is correct, but there is a security (and thus mandatory) update for it coming in less than a month (as a part of [Oracle April CPU](https://www.oracle.com/technetwork/topics/security/alerts-086861.html)). I am going to release jdk10 builds (with that update) around the end of April.

**Comment by marcomsousa** [comment]
Ok, but there are security updates every 3 or 4 months for all support java versions.
April, July, October, January

Remember that J**DK9 is already deprecated and without support**.
http://www.oracle.com/technetwork/java/eol-135779.html

**Oracle recommend that App using Java 9 migrate to Java 10 now**, not in April.

**Comment by ojdkbuild** [comment]
Oracle is a main company behind OpenJDK, but not the only one. Depending on where you are getting the JDK binaries you use for your apps, the notion of "support" may have different meanings. For example, JDK6 is still [supported and updated regularly](http://mail.openjdk.java.net/pipermail/jdk6-dev/2018-March/003671.html).

> Oracle recommend that App using Java 9 migrate to Java 10 now, not in April.

"ojdkbuild project" recommends to stay on JDK8, that is a long term release that is going to be supported at least until October 2020. And then to move to the next LTS release (JDK11) only after it receives a couple of minor updates.

**Comment by marcomsousa** [comment]
thank you for your clarification

**Comment by ojdkbuild** [comment]
[10.0.1 release](https://github.com/ojdkbuild/ojdkbuild/releases/tag/10.0.1-1) is ready, announce with a description will follow shortly.

**Comment by ojdkbuild** [comment]
[announcement](https://groups.google.com/forum/#!msg/ojdkbuild/dKayJ0T4lME/x96eiTf1DAAJ) posted, closing the issue.
