### ISSUE TITLE
javaws error message

### ISSUE THREAD

**Issue by ecki** [ojdkbuild/ojdkbuild#35]
When starting javaws.exe with no argument a error screen is shown. First of all the error is rather missleading ("ojdkbuild WebStart was unable to start Java VM"). The actual reason ("No arguments specified") is hidden.

I think for this specific case a more specific error message should be shown and more generally the error dialog should be more like "ojdkbuild WebStart problem" or similiar (less JVM specific).

![image](https://user-images.githubusercontent.com/361432/41318445-9c4d2082-6e98-11e8-9e6a-316e1cf020af.png)

Another thing, the linked Wiki page refers to the RedHat log folder. However for the ojdkbuild disctribution he log fiels are found in the odjkbuild directory instead. Maybe RedHat build should point to a different page?

**Comment by ojdkbuild** [comment]
Hi,

On error dialog - yes, it is kind of a "generic" dialog that just displays any error that may happen during the startup. I agree, that more specific error message for the "double-click it" use case would be better. Will look into it. Generally this exe launcher is expected to be used only with shell (win explorer, browser) integration. To run a JNLP manually from console it may be better to use a `javaws.jar` directly.

On wiki page - thanks for the pointer! `RedHat` directory name was incorrect there, just fixed it in wiki. Generally ojdkbuild builds must have no RH references (and RH builds should have minimum ojdkbuild references), but some of these references (in labels, links etc) may leak sometimes.

> Maybe RedHat build should point to a different page?

M, just checked this, RH build actually correctly points to [this link](https://developers.redhat.com/products/openjdk/overview/#_webstart).

PS: while checking this found that this dialog is broken in 32-bit webstart launcher. While 32-bit builds are much less supported, than 64-bit ones, this still must be fixed, filed #36.

**Comment by ecki** [comment]
How about not producing anerror when no argument is specified but just call the Java.exe with the -about option? (and fix the missing resources for that dialog).

**Comment by ojdkbuild** [comment]
M, I do not want to call Java when error need to be reported to user, because (in theory) java startup may fail too. Though, the case for no-arg launch (double-click) may be an exception to this, because it is not really an error. Going to fix this either way before the next release in the end of July.

**Comment by ojdkbuild** [comment]
I the end I just changed (in 8u181) the message for "double-click" error to:

"This application is not intended to be used directly. Please run JNLP from a web-browser or from a file explorer."

Hopefully this should be less confusing to users, closing the issue.
