### ISSUE TITLE
x86_64 msi installer fails with error code 2932

### ISSUE THREAD

**Issue by austinw-fineart** [ojdkbuild/ojdkbuild#40]
Tested using java-10-openjdk-10.0.2-1.b13.ojdkbuild.windows.x86_64.msi

### Event Viewer
`
Product: OpenJDK 1.10.0_2-1-ojdkbuild -- The installer has encountered an  unexpected error installing this package. This may indicate a problem with this  package. The error code is 2932. The arguments are:  C:\Users\Austin.W\AppData\Roaming\Microsoft\Installer\{8F611211-D457-40B6-8765-7404372C9BDC}\_b0950439_e1e2_4172_b679_40b6604c2d50,  5,
`
### OS version
Windows 10 (1803)

**Comment by ojdkbuild** [comment]
Hi, thanks for the report! Any details how to reproduce this? It installs successfully for me on both win10 and win7, tried both clean install an update from 10.0.1.

**Comment by austinw-fineart** [comment]
Here is the log file as well:
[MSId11d5.zip](https://github.com/ojdkbuild/ojdkbuild/files/2251747/MSId11d5.zip)

**Comment by ojdkbuild** [comment]
Thanks for the log! Error message from it:

> MSI (s) (A0:BC) [09:38:26:566]: Executing op: IconCreate(Icon=_b0950439_e1e2_4172_b679_40b6604c2d50,Data=BinaryData)
1: _b0950439_e1e2_4172_b679_40b6604c2d50 
DEBUG: Error 2932:  Could not create file C:\Users\Austin.W\AppData\Roaming\Microsoft\Installer\{8F611211-D457-40B6-8765-7404372C9BDC}\_b0950439_e1e2_4172_b679_40b6604c2d50 from script data. Error: 5
The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2932. The arguments are: C:\Users\Austin.W\AppData\Roaming\Microsoft\Installer\{8F611211-D457-40B6-8765-7404372C9BDC}\_b0950439_e1e2_4172_b679_40b6604c2d50, 5, 
MSI (s) (A0:BC) [09:38:27:624]: Product: OpenJDK 1.10.0_2-1-ojdkbuild -- The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2932. The arguments are: C:\Users\Austin.W\AppData\Roaming\Microsoft\Installer\{8F611211-D457-40B6-8765-7404372C9BDC}\_b0950439_e1e2_4172_b679_40b6604c2d50, 5, 

> MSI (s) (A0:BC) [09:38:27:625]: Note: 1: 2318 2: C:\Users\Austin.W\AppData\Roaming\Microsoft\Installer\{8F611211-D457-40B6-8765-7404372C9BDC}\_b0950439_e1e2_4172_b679_40b6604c2d50 
DEBUG: Error 2318:  File does not exist: C:\Users\Austin.W\AppData\Roaming\Microsoft\Installer\{8F611211-D457-40B6-8765-7404372C9BDC}\_b0950439_e1e2_4172_b679_40b6604c2d50
The installer has encountered an unexpected error installing this package. This may indicate a problem with this package. The error code is 2318. The arguments are: C:\Users\Austin.W\AppData\Roaming\Microsoft\Installer\{8F611211-D457-40B6-8765-7404372C9BDC}\_b0950439_e1e2_4172_b679_40b6604c2d50, , 
Action ended 9:38:27: InstallFinalize. Return value 3.

"Error 5: Access is Denied" indicates that for some reason installer cannot create a temporary file.

It is hard to do something here without the locally-reproducible recipe. I close the issue, please reopen if any more details on this appear.
