### ISSUE TITLE
Library linking on windows

### ISSUE THREAD

**Issue by NanoNik** [ojdkbuild/ojdkbuild#41]
Is there's any way to link all DLL's in one (jvm.dll for example)?

**Comment by do-hyeon89** [comment]
which problem do you haved?
________________________________
보낸 사람: Nan0 <notifications@github.com>
보낸 날짜: 2018년 8월 17일 금요일 오전 6:36
받는 사람: ojdkbuild/ojdkbuild
참조: Subscribed
제목: [ojdkbuild/ojdkbuild] Library linking on windows (#41)


Is there's any way to link all DLL's in one (jvm.dll for example)?

**Comment by NanoNik** [comment]
I'm trying to link all object files manually, but I get a lot of errors and unresolved dependencies

**Comment by rednoah** [comment]
Yes, but why are you doing this? What is the problem? What is the goal you want to achieve? How does having a single `jvm.dll` help you achieve this goal?

**Comment by ojdkbuild** [comment]
Hi, I think this is possible in theory, but OpenJDK build system is quite complex and there are a lot of places in jdk Java code where DLLs are loaded by their current names.

For "single-binary", depending on the use case, it may be better to look to app bundlers (like [launch4j](http://launch4j.sourceforge.net/)) or to AOT pre-compilation with [Graal native images](https://www.graalvm.org/docs/reference-manual/aot-compilation/) (that have a number of limitations).

**Comment by NanoNik** [comment]
Unfortunately, both of this projects unsuitable for my aims, so if no one can help me, I'll be trying to build OpenJDK in "single-binary" by myself
