### ISSUE TITLE
Q: Senandoah GC VM Builds?

### ISSUE THREAD

**Issue by xGnoSiSx** [ojdkbuild/ojdkbuild#43]
Hello,

Just a short question:
do you plan to support  builds that will include the Shenandoah GC for the VM? 

Also, since you;re maintaining win-x64 builds, would you provide one with the Shenandoah GC?

My questions only stem from the fact that I've seen no builds whatsoever that include the Shenandoah GC for win-x64. If you know of such a project, please direct me there!

Thank you!

**Comment by ojdkbuild** [comment]
Hi, jdk8-win-x64 builds in this project include Shenandoah GC starting with 8u144, `-XX:+UseShenandoahGC` flag needs to be used to enable it.

**Comment by xGnoSiSx** [comment]
I gave it a spin and indeed it works in jdk8!! Many thanks for the info & the build.

Will this be part of this projects ojdk 11 build when it comes out? I also note that this GC is not included in ojdk 10.

**Comment by ojdkbuild** [comment]
Yes, it is going to be included with jdk11 release in October.

jdk10 being a short-term-release didn't have a corresponding package in CentOS 7, upstream sources were used for it instead which doesn't include Shenandoah.

**Comment by ojdkbuild** [comment]
Closing the issue, please feel free to re-open with more Shenandoah questions.
