### ISSUE TITLE
Any chance of running on Windows XP(Java 9 or Java 10)?

### ISSUE THREAD

**Issue by malikoski** [ojdkbuild/ojdkbuild#47]
In XP: java.exe is not a valid Win32 application.

**Comment by ojdkbuild** [comment]
Hi, no, while jdk8 should run fine on WinXP, jdk9 and 10 are compiled with vs2013 without including XP compatibility. And jdk11 is not going to have 32-bit version at all, citing from [here](http://mail.openjdk.java.net/pipermail/build-dev/2018-September/023270.html):

>> On a meta-level: Is a JDK for Windows 32-bit just built no longer or is
>> it completely abandoned as a platform?

> Oracle is not building 32-bit Windows regularly, and I don't think 
anyone else is doing that. (Perhaps AdoptOpenJDK?) In such a scenario, 
the code quickly bit rots. There has been no decision as of yet to 
remove the code from the code base, but unless someone steps up to 
maintain the code base, it's unlikely to survive in the long term.

**Comment by malikoski** [comment]
Ok.. thanks.

**Comment by andvasp** [comment]
Hi @ojdkbuild !

Do you know if is possible to build the jdk 11 by my self using the source code to support windows XP?

Thanks in advance!

**Comment by ojdkbuild** [comment]
Hi, it is possible in theory, if compiler is configured to use "v120_xp", it will produce binaries compatible with XP. Just for jdk11 it would require a bit of code patching, most probably in networking and FS parts that are using some features only available on Vista+ (symlinks etc).

**Comment by andvasp** [comment]
Pretty good to know!

Thanks!
