### ISSUE TITLE
JNLP support aka Webstart in openjdk ?

### ISSUE THREAD

**Issue by btreut** [ojdkbuild/ojdkbuild#48]
according to the [wiki](https://github.com/ojdkbuild/ojdkbuild/wiki/WebStart), JNLP support/webstart should be included since 8_151 but I cannot find any traces of it in java-1.8.0-openjdk-1.8.0.151-1.b12.ojdkbuild.windows.x86_64.zip or java-1.8.0-openjdk-1.8.0.181-1.b13.ojdkbuild.windows.x86_64.zip. There is neither a javaws.{bat,cmd,exe} nor netx.jar.

Following some recipes in Chap. 7 of the [OpenJDK cookbook](https://www.packtpub.com/application-development/openjdk-cookbook), I succeeded in getting something like itweb-settings GUI and was able to start a local jnlp file, but my scripts for starting both are very crude and ad hoc hacks, so I tried to look for better ones from the ojdkbuild. Sorrily I could not find anything in the 8_151/8_181 zip archives.

**Comment by ojdkbuild** [comment]
Hi, WebStart component is included with jdk8 MSI installer, there is no separate ZIP download for it. It consists of IcedTea-Web (that is based on NetX) JAR, EXE launcher for it and windows registry settings that allows to run JNLP files and "jnlp://" links directly from web-browser.

**Comment by btreut** [comment]
thanks. I had hoped that the zip included the skripts.
