### ISSUE TITLE
OpenJDK can't support render text with rotation for DBCS fonts

### ISSUE THREAD

**Issue by linxingyun** [ojdkbuild/ojdkbuild#5]
OpenJDK has bug on DBCS fonts’ support: it can’t support to render text with rotation for the fonts like: MingLiu, HeiT, MS PGothic, MS PMincho, Batang and Gulim. 

Because I am not able to enter bug in the offical OpenJDK website, I am entering bug here to see if you could help to help to redirect this problem to a proper guy to handle it. Thanks a lot!

Below is the sample code to reproduce the problem:

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.File;

import javax.imageio.ImageIO;

public class TestFontRender {

	private static final String IMAGE_TYPE="png";
	// You may need to change the filepath below in order to save the image in proper path.
	private static final String IMAGE_FILEPATH="c:\fontRender_openjdk.png";
	
	/**
	 * @param args
	 */
	public static void main(String[] args) {
		
		TestFontRender code = new TestFontRender();
		BufferedImage bufferImage = code.getImage();
		code.saveImage(bufferImage, IMAGE_TYPE, IMAGE_FILEPATH);
	}

	public BufferedImage getImage() {
		int width = 800;
		int height = 600;
		int degree = -90;
		BufferedImage image = new BufferedImage(width, height,
				BufferedImage.TYPE_INT_RGB);

		Graphics g = image.getGraphics();

		Color background = new Color(255, 255, 255);
		g.setColor(background);
		g.fillRect(0, 0, width, height);

		g.setColor(getColor());
		g.drawRect(0, 0, width - 1, height - 1);

		Color textColor = new Color(255, 0, 0);
		g.setColor(textColor);
		
		//"MS PGothic" font
		String text = "Height (日本平均)アイウ MS PGothic angle=0";
		Font textFont = new Font("MS PGothic",Font.PLAIN,14);
		g.setFont(textFont);
		Graphics2D g2d_1 = (Graphics2D) g.create();
		g2d_1.translate(20, 20);
		g2d_1.drawString(text, 0, 0);
		
		g2d_1.translate(20, 300);
		g2d_1.rotate(degree * Math.PI / 180);
		text = "Height (日本平均)アイウ MS PGothic angle=-90";		
		g2d_1.drawString(text, 0, 0);

		//"MS PMincho" font
		text = "Height (日本平均)アイウ MS PMincho angle=0";
		textFont = new Font("MS PMincho",Font.PLAIN,14);
		g.setFont(textFont);
		Graphics2D g2d_2 = (Graphics2D) g.create();
		g2d_2.translate(85, 55);
		g2d_2.drawString(text, 0, 0);
		
		g2d_2.translate(55, 300);
		g2d_2.rotate(degree * Math.PI / 180);
		text = "Height (日本平均)アイウ MS PMincho angle=-90";
		g2d_2.drawString(text, 0, 0);
		
		
		//"Gulim"  font 
		text = "Height (Korea) Gulim angle=0";
		textFont = new Font("Gulim",Font.PLAIN,14);
		g.setFont(textFont);
		Graphics2D g2d_3 = (Graphics2D) g.create();
		g2d_3.translate(145, 85);
		g2d_3.drawString(text, 0, 0);
		
		g2d_3.translate(85, 300);
		g2d_3.rotate(degree * Math.PI / 180);
		text = "Height (Korea) Gulim angle=-90";
		g2d_3.drawString(text, 0, 0);
		
		
		//"HeiT"  font 
		text = "Height (平均) HeiT angle=0";
		textFont = new Font("HeiT",Font.PLAIN,14);
		g.setFont(textFont);
		Graphics2D g2d_4 = (Graphics2D) g.create();
		g2d_4.translate(200, 115);
		g2d_4.drawString(text, 0, 0);
		
		g2d_4.translate(115, 300);
		g2d_4.rotate(degree * Math.PI / 180);
		text = "Height (平均) HeiT angle=-90";
		g2d_4.drawString(text, 0, 0);
				
		
		g.dispose();
		return image;
	}

	private Color getColor() {
		int R = (int) (Math.random() * 255);
		int G = (int) (Math.random() * 255);
		int B = (int) (Math.random() * 255);
		return new Color(R, G, B);
	}

	public void saveImage(BufferedImage image, String format, String filePath) {
		try {
			ImageIO.write(image, format, new File(filePath));
		} catch (Exception e) {
			throw new RuntimeException(e);
		}
	}

}

**Comment by ojdkbuild** [comment]
Thanks for this report! I will investigate it and will bring it to upstream OpenJDK bugtracker after that.

**Comment by ojdkbuild** [comment]
@linxingyun , I filed https://bugs.openjdk.java.net/browse/JDK-8163278 . If you'd like to add something to the issue, you may post the details here - I will forward them to upstream issue.

To get more attention to the issue you can also post it to http://mail.openjdk.java.net/mailman/listinfo/awt-dev list. Though issue seems to be specific to OpenJDK on windows, and, as OracleJDK and OpenJDK in RHEL are not affected, it may not receive much interest from Oracle/RedHat devs.

I myself won't be able to look into details in the following weeks - will continue with it in September.

**Comment by linxingyun** [comment]
@ojdkbuild Thanks a lot for the help on filing the defect!

One more thing I would like to add is: this problem could be reproduced in both Windows and Linux.  And note that we need to make sure those DBCS fonts as mentioned need to be installed in operating system so that we could see the exact problem. 

Thanks again for the help!

**Comment by ojdkbuild** [comment]
@linxingyun Thanks for the update! I was wrong about RHEL, added your comment and output examples to the issue.

**Comment by linxingyun** [comment]
@ojdkbuild Thanks a lot for your help on the updating!

**Comment by ojdkbuild** [comment]
Patch for this problem was [posted upstream](https://bugs.openjdk.java.net/browse/JDK-8163278?focusedCommentId=13999670&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13999670). It worked for me both on RHEL and on Windows. I included this patch into [8u102-2](https://github.com/ojdkbuild/ojdkbuild/releases/tag/1.8.0.102-2) windows build.

I am closing this issue, please reopen it if won't work with 8u102-2.

**Comment by linxingyun** [comment]
@ojdkbuild  Thanks! 
I saw that defect (https://bugs.openjdk.java.net/browse/JDK-8163278) is still in open status. Do you know which official version of  OpenJDK (for linux)  will contain this fix?

**Comment by ojdkbuild** [comment]
@linxingyun given the feature-complete state of OpenJDK 9 - cannot say for sure. Generally such fix should go into the latest dev version (jdk10 once its repos will be available) and then to be backported to the update releases of jdk9 and 8. Linux distros maintainers can include the patch earlier with their builds though.

**Comment by linxingyun** [comment]
@ojdkbuild Thanks a lot for the help!
Do you know the timeline of  jdk10?   
And does the image "1.8.0_111" version for Linux as you provided contain this fix? Thank you!

**Comment by ojdkbuild** [comment]
@linxingyun , I think jdk10 timeline is not yet determined (here is one for jdk9: http://openjdk.java.net/projects/jdk9/ ). 

No, this Linux bundle is created from CentOS 6 "as-is", patch is not applied there. Patches inclusion is generally on discretion of Linux distro-maintainers, it may worth it creating an issue about this patch in the bugtracker of the distro you use (for CentOS it probably should be a Fedora one - https://fedoraproject.org/wiki/Bugzilla ).
