### ISSUE TITLE
Windows Installer not setting JAVA_HOME environment variable

### ISSUE THREAD

**Issue by andi-blafasl** [ojdkbuild/ojdkbuild#53]
After installing java-1.8.0-openjdk-1.8.0.191-1.b12.ojdkbuild.windows.x86_64.msi I had to set the environment variable JAVA_HOME by myself to get some application working.
I think it would be good to have the installer setting this.

**Comment by ojdkbuild** [comment]
Hi, beginning with 8u191 and 11.0.1 MSI installers include optional support for setting `JAVA_HOME`. It is off by default, needs to be enabled manually during the installation.

For automated MSI installs see `jdk_env_java_home` feature [here](https://github.com/ojdkbuild/ojdkbuild/issues/49) and [here](https://github.com/ojdkbuild/ojdkbuild/wiki/InstallerFeatures).

**Comment by andi-blafasl** [comment]
Thank you so much for pointing me to this feature. I did a custom installation but missed this option. I will take a look at the automated installation and test it with our management tool Baramundi.
