### ISSUE TITLE
Cisco ASDM not working with ojdkbuild

### ISSUE THREAD

**Issue by andi-blafasl** [ojdkbuild/ojdkbuild#54]
Not sure if this is the right place for the issue, but it could be fixed with little afford.

If I try to start the CISCO asdm with javaws.exe on Windows it fails with the following error message:

```
net.sourceforge.jnlp.LaunchException: Fatal: Startfehler: Konnte JNLP-Datei nicht starten. Die Anwendung war nicht initialisiert. Um detailierte Informationen zu erhalten können javaws oder der Web-Browser von der Befehlszeile aus gestartet werden und die Textausgabe in einem Fehlerbericht gesendet werden.
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:577)
	at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:940)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:571)
	... 1 more
Caused by: java.lang.ExceptionInInitializerError
	at com.cisco.launcher.s.if(Unknown Source)
	at com.cisco.launcher.Launcher.main(Unknown Source)
	... 6 more
Caused by: java.lang.NumberFormatException: For input string: "191-1-ojdkbuild"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.parseInt(Integer.java:615)
	at com.cisco.launcher.ClassUtil.<clinit>(Unknown Source)
	... 8 more
```

Doing the same with an openjdk on ubuntu linux (jre from the repository) it is working like a charm.

As far as I understand it is the version string returned by the java build.
On Linux I get:
```
user@host:~# java -version
openjdk version "1.8.0_181"
OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-1ubuntu0.16.04.1-b13)
OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
```

On windows with the latest ojdkbuild:
```
C:\java -version
openjdk version "1.8.0_191-1-ojdkbuild"
OpenJDK Runtime Environment (build 1.8.0_191-1-ojdkbuild-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)
```

Best regards,
Andreas

**Comment by ojdkbuild** [comment]
That is unfortunate, ojdkbuild doesn't use any special hacks for version string - it is formed from configure arguments that are well-supported upstream. So current version string is fully legal for jdk8 and I'd like to keep it in its current form. But it seems that some apps have overly strict checks for that string. I don't see any easy solutions without changing the version detection logic inside the app (that is obviously not always possible).

As a quick workaround, you can install ojdkbuild MSI including WebStart and then replace the contents of jdk installation directory with some other jdk (with compatible version string) leaving `webstart` directory intact. That way WebStart should continue working with this new jdk. This can break uninstall logic though (may need to cleanup the dir manually after the uninstall).

**Comment by andi-blafasl** [comment]
That's very bad to hear. Every openjdk build in every Linux distribution and other windows builds I'm testing is using a version number similar to "1.8.0_181" 
```
C:\Program Files\Amazon Corretto\jre8\bin\java -version
openjdk version "1.8.0_192"
OpenJDK Runtime Environment (build 1.8.0_192-amazon-corretto-preview-b12)
OpenJDK 64-Bit Server VM (build 25.192-b12, mixed mode)

E:\zulu8.33.0.1-jdk8.0.192-win_x64\jre\bin\java -version
openjdk version "1.8.0_192"
OpenJDK Runtime Environment (Zulu 8.33.0.1-win64) (build 1.8.0_192-b01)
OpenJDK 64-Bit Server VM (Zulu 8.33.0.1-win64) (build 25.192-b01, mixed mode)

E:\jdk8u192-b12\jre\bin\java -version
openjdk version "1.8.0_192"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_192-b12)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.192-b12, mixed mode)

E:\jdk-11.0.1\bin\java -version
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)
```

The bad thing with all these builds -> they do not support jnlp java web start :-(

That's why I was hoping to get it working with ojdkbuild 👍

**Comment by andi-blafasl** [comment]
I found this information about a similar problem in the AdoptOpenJDK Project

https://github.com/AdoptOpenJDK/openjdk-build/issues/205

as you can see in my last comment, they changed their version string ;-)

**Comment by ojdkbuild** [comment]
Currently there are no plans to change version string for jdk8, closing this as "wontfix".

**Comment by ojdkbuild** [comment]
Re-opening this. Version string was changed in October 2019 update (8u232, 11.0.5, 13.0.2) and it no longer contains "ojdkbuild" label.

**Comment by ojdkbuild** [comment]
Closing as "fixed".
