### ISSUE TITLE
Openjdk 11 on 32 bits

### ISSUE THREAD

**Issue by nfouka** [ojdkbuild/ojdkbuild#58]
Its possible to build a 32 bits for OpenJDK 11 ?

**Comment by rednoah** [comment]
`Windows 10 ARM` would be interesting as well, if possible at all. I rely on 32-bit primarily because that one works on ARM Windows via binary translation.

**Comment by 1of16** [comment]
no, since there is no x86 openjdk, as far as I know: https://jdk.java.net/11/
and I thought @ojdkbuild already told us in another issue, there won't be any x86 build for java 11

**Comment by rednoah** [comment]
Well, I wouldn't go by the OpenJDK download page alone, since `linux-armhf` and `linux-aarch64` binaries aren't there either.

**Comment by gitoss** [comment]
Lookie here: https://github.com/ojdkbuild/ojdkbuild/issues/38 ... x86 is possible in theory, but there's no one around to implement/update it since Oracle dropped it. The Windows on ARM argument is interesting though, maybe that's a reason someone might be interested to work on it.

**Comment by nfouka** [comment]
thank you for your answer ! I finally chose the jdk10 with 32 build .

**Comment by nfouka** [comment]
This is a version that is pretty to jdk 11

**Comment by ojdkbuild** [comment]
Just for the record, example of the issues that started to appear in win_x86 (32-bit) builds - https://mail.openjdk.java.net/pipermail/hotspot-runtime-dev/2019-March/033271.html

**Comment by gitoss** [comment]
But this mailing list posting basically says that you can still build x86 Java11?

Anyway, so much for Java being uninversal. On my x86 win10 laptop (b/c only 2gb of ram) I cannot use apps anymore that are important to me like Cryptmator :-\

**Comment by gitoss** [comment]
BREAKING: AdoptOpenJDK still builds x86, even Java12 is available :-) https://adoptopenjdk.net/

**Comment by 1of16** [comment]
without webstart it is not really useful for me...but ain't got any need for x86...
