### ISSUE TITLE
Add OpenJFX binaries

### ISSUE THREAD

**Issue by ghost** [ojdkbuild/ojdkbuild#6]
I think sould be fine to add OpenJFX binaries for Windows too.

**Comment by ojdkbuild** [comment]
Sorry, that's not possible currently. I am doing windows builds to match CentOS/RHEL ones, and there is no OpenJFX in RHEL. It is not even in Fedora (that often serves as an "incubator" for RHEL) yet - https://ask.fedoraproject.org/en/question/63037/is-there-openjfx-for-fedora-yet/ .

While building OpenJFX shouldn't be that hard, maintaining such build is not a small task - I cannot do that as a part of this project. IMO the proper way to move this forward will be to ping Fedora devs. So closing as "wontfix".

**Comment by ojdkbuild** [comment]
OpenJFX [landed to Fedora](https://bugzilla.redhat.com/show_bug.cgi?id=1438673), reopening the issue.

Initial OpenJFX builds are going to be done without "WebView" component that requires WebKit.

Currently there is no ETA for including OpenJFX into stable and supported builds.

**Comment by ojdkbuild** [comment]
Uploaded experimental OpenJFX 8 binaries, [announcement](https://groups.google.com/d/msg/ojdkbuild/SlcISRms4h8/FwlZnfj9AAAJ). Closing this issue, please open separate issues for OpenJFX bugs/requests as needed.

**Comment by ojdkbuild** [comment]
As a "heads up" for interested parties - full version of OpenJFX-8 is included with 8u161, [announcement](https://groups.google.com/d/msg/ojdkbuild/fdAaLvV5PRM/LZAZsX19AwAJ). Now debug builds are pending for OpenJFX-8 to become feature-complete.
