### ISSUE TITLE
Garbled UTF-8 characters from JNLP files only in Windows (not Linux)

### ISSUE THREAD

**Issue by robert-scheck** [ojdkbuild/ojdkbuild#60]
When using WebStart from `java-1.8.0-openjdk-1.8.0.201-1.b09.ojdkbuild.windows.x86_64.msi`, I noticed that (German) UTF-8 characters inside of JNLP files are displayed garbled during the WebStart loading screen – but just under Microsoft Windows 7 and not under Linux (CentOS 7.6 with `icedtea-web-1.7.1-1.el7.x86_64`). Optically it feels like they are treated as ISO-8859-1 rather UTF-8.

However, the web server sends a proper HTTP header (same test for Windows and Linux):

```
Content-Type: application/x-java-jnlp-file; charset=utf-8
```

And the JNLP file contains some regular UTF-8 characters here and there:

```
<?xml version="1.0" encoding="utf-8"?>
<jnlp spec="1.6.0+" codebase="http://example.net" href="jnlp/">
  <information>
    <title>Test äöüß</title>
    <vendor>Test äöüß</vendor>
    <homepage href="http://exämple.net/" />
    <description>Test äöüß</description>
  </information>
  <update check="always" policy="always" />
  <security>
    <all-permissions />
  </security>
  <resources>
    <j2se version="1.6.0+" />
    <jar href="example.jar" part="true" main="true" />
    <jar href="example2.jar" part="true" />
  </resources>
  <application-desc main-class="example.main">
    <argument>http://example.net/java/</argument>
  </application-desc>
</jnlp>
```

**Comment by ojdkbuild** [comment]
Thanks for the report, I can reproduce this locally. Going to fix this.

**Comment by ojdkbuild** [comment]
This is a problem with tagsoup library usage, that is used for parsing possibly malformed JNLP XML. If no encoding is specified, it [uses autodetector](https://github.com/ojdkbuild/lookaside_tagsoup/blob/4f7eff8b36a6154d20b5fbf2c47b9e140d92c65a/src/java/org/ccil/cowan/tagsoup/Parser.java#L490) that [uses default platform encoding](https://github.com/ojdkbuild/lookaside_tagsoup/blob/4f7eff8b36a6154d20b5fbf2c47b9e140d92c65a/src/java/org/ccil/cowan/tagsoup/Parser.java#L463).  

Added [enforcing of UTF-8](https://github.com/ojdkbuild/lookaside_icedtea-web/commit/b826fa070c03a6e6423312aea694a1ed1e0f5cb1), it is going to be included with 8u211 in April. Also attaching updated [javaws.jar](https://github.com/ojdkbuild/ojdkbuild/files/2824809/javaws.jar.zip) with this fix.

**Comment by ojdkbuild** [comment]
Closing this as "fixed".
