### ISSUE TITLE
No IcedTea-Web (Java Web Start / javaws.exe) in 11.0.x

### ISSUE THREAD

**Issue by robert-scheck** [ojdkbuild/ojdkbuild#61]
Currently `java-11-openjdk-11.0.2.7-1.windows.ojdkbuild.x86_64.msi` doesn't ship IcedTea-Web (Java Web Start / `javaws.exe`), while `java-1.8.0-openjdk-1.8.0.201-1.b09.ojdkbuild.windows.x86_64.msi` indeed does (thank you!). Is there a specific reason that IcedTea-Web is missing in ojdkbuild 11.0.x?

However, https://developers.redhat.com/products/openjdk/overview/ says (where I assume that ojdkbuild might be the technical upstream for the Red Hat builds), there would be IcedTea-Web for OpenJDK 11 though:

> **Web Start**
> OpenJDK 11 Windows installer includes an additional component - Web Start deployment protocol implementation based on IcedTea-Web open-source project.
> 
> IcedTea bugtracker may be used to report issues with Web Start on Windows. Please include the appropriate details about the problematic Web Start application from "%LOCALAPPDATA%\RedHat\java-1.11.0-openjdk-[version]\webstart\javaws_last_log.txt" log file.

Interestingly, I can not find any `javaws.exe` anywhere after installation of `java-11-openjdk-11.0.1.13-1.redhat.windows.x86_64.msi`. In difference to that, installing `java-1.8.0-openjdk-1.8.0.191-1.b12.redhat.windows.x86_64.msi` leads to a `javaws.exe`. Is this a Red Hat marketing mistake and the website should say "OpenJDK 8 Windows installer" rather "OpenJDK 11 Windows installer"?

**Comment by ojdkbuild** [comment]
Yes, the page on developers.redhat.com was updated incorrectly, it should be "OpenJDK 8 Windows installer" and "java-1.8.0-openjdk". I will report this to RH DevPortal people.

About ITW and jdk11 - it was planned to be included into MSI with one of the jdk11 updates. But upstream ITW does not work properly with jdk11 yet. It is not clear whether it will be ready for jdk11-win in foreseeable future. So currently jdk8 is the only option for ITW.

**Comment by robert-scheck** [comment]
I simply tried your OpenJDK 11 build with IcedTea-Web 1.7.1 but ended with a freezing Java Web Start confirmation dialog (after authentication but before launching) and the following message on `cmd.exe`:

```
sun.misc.Launcher not found. Running jdk9 or higher? Using unsecure BootClassLoader
```

Seems to origin at http://mail.openjdk.java.net/pipermail/distro-pkg-dev/2016-November/037196.html

**Comment by ojdkbuild** [comment]
Last time I tried it [with additional modules flags](https://github.com/ojdkbuild/contrib_itw-launcher/commit/01d2140760d5705871d98f7377b448a64cb80261#diff-45ddd7319b2d5e155654008d4d515d07) ITW upstream tip didn't work on windows. Going to add support for reading JVM flags from a config file (currently all flags are hardcoded inside the launcher) to experiment with these flags easier.

**Comment by ojdkbuild** [comment]
Reported the problem about the DevPortal page, not sure how long it will take for the correction to go live, closing the issue.
