### ISSUE TITLE
Problem in "Other obsolete downloads - windows x86 section" 

### ISSUE THREAD

**Issue by Anshulwebdevs** [ojdkbuild/ojdkbuild#64]
In x86 section openjdk 11 for 64-bit windows is provided. It should be for x86 since it is in x86 section.
I need openjdk 11 for 32-bit machine please help.

**Comment by 1of16** [comment]
Hi,
take a look here: https://github.com/ojdkbuild/ojdkbuild/issues/58#issuecomment-450677733
there is no x86 build for java 11 and I guess there wont be any.

**Comment by ojdkbuild** [comment]
@Anshulwebdevs , jdk11-x86_64 was incorrectly appended to the x86 list of obsolete downloads. Just changed it in readme moving it to x86_64 list. There is indeed no 32-bit version of jdk11 and there are no plans to introduce it.
