### ISSUE TITLE
Migration to organization

### ISSUE THREAD

**Issue by Neustradamus** [ojdkbuild/ojdkbuild#66]
It is possible to migrate the personal account to organization?
- https://help.github.com/articles/converting-a-user-into-an-organization/

**Comment by ojdkbuild** [comment]
M, I assume GitHub organization may be more convenient (than a personal account) when there exists a considerable number of committers. I don't think this is necessary for this project.

**Comment by Neustradamus** [comment]
ojdkbuild is a nice project which needs to be more known and developped ^^

**Comment by 0xbaadf00d** [comment]
By using "ojdkbuild" for your username and repository name, you already act as an organisation. It could be interresting to migrate to organization, create teams (Owner, Maintainers, Mergers, Advisors, ...) even if for this moment, you are alone on this project. You could open a website to promote this project and get a better interface than Github for "non-developer" people

**Comment by bugabinga** [comment]
@thibaultmeyer why would any "non-developer" be interested in a JDK?

**Comment by ojdkbuild** [comment]
Given the following: 

 - in the whole this github project, only the root repo is an actual "github repository" (have releases, issues, wiki) and all other repos are "dumb" submodules of that repo

 - [conversion to organization](https://help.github.com/en/articles/converting-a-user-into-an-organization) is a one-way process: `An organization cannot be converted back to a user` 

I think the migration to organization is currently not necessary.

**Comment by Neustradamus** [comment]
You must not closed this ticket if it is not done...

**Comment by ojdkbuild** [comment]
It was closed as "won't fix".

**Comment by Neustradamus** [comment]
I do not understand why...
There is no problem to migrate...
A lot of have been done without problems...

**Comment by ojdkbuild** [comment]
Sorry, I see nothing wrong with github organization per se, just I don't think it is necessary for the account with only one single "top-level" repository.

**Comment by Neustradamus** [comment]
@ojdkbuild: I think that the best solution is (in few minutes):
- Change your username to ojdkbuildaccount (or other): https://github.com/settings/admin
- Create ojdkbuild organization: https://github.com/organizations/new

And:
- Transfer ojdkbuild into ojdkbuild org: https://github.com/NEWACCOUNTUSERNAME/ojdkbuild/settings

No lost, you can see, for examples:
- https://github.com/nerzhul/ocsms
- https://github.com/tigaseinc/tigase-server

cc: @thibaultmeyer, @bugabinga.

**Comment by ojdkbuild** [comment]
Landscape for OpenJDK builds and OpenJDK presence on GitHub today is quite different comparing with 5 years ago when this project was started. Existing and upcoming LTS builds are going to continue being published here, but otherwise there are no plans to have additional builds (MTS like jdk13 or STS like jdk16) or to promote this project somehow (like converting to organization and inviting members). It may be better to use https://github.com/openjdk as a main and official OpenJDK place instead.

**Comment by Neustradamus** [comment]
@ojdkbuild: The goal is to have a best place, currently it is not good, it will the renaming, the creation of the org (and add members), and the transfer of this repo.

After you can rename the account by your personal username (if you have not) or remove the account.

**Comment by bugabinga** [comment]
@ojdkbuild Thanks for maintaining this project. It is very much appreciated.
Would you mind copy and pasting your last message into the README?

I do not really understand the benefit of an organisation, especially in the case on one project maintained by one person.

**Comment by Neustradamus** [comment]
@bugabinga: Thanks for your reply.

Some links:
- https://help.github.com/en/github/getting-started-with-github/types-of-github-accounts
- https://github.community/t/best-practices-for-organizations/10205
- https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams

**Comment by ojdkbuild** [comment]
@bugabinga , you are welcome, added the note to the "About" in readme.

**Comment by Neustradamus** [comment]
We can see here:
- https://i.ibb.co/P1VhGn8/ojdkbuild-contributors.png

Contributors are @akashche, @stooke, @daudo, @acornett.

We can see that @ojdkbuild personal account is a false account.
-> It is totally possible to change this @ojdkbuild personal account to an organization account.
