### ISSUE TITLE
Are all JDK 8 and 11 builds LTS versions, or only the windows builds?

### ISSUE THREAD

**Issue by mpe85** [ojdkbuild/ojdkbuild#69]
According to the top-level README.md, the JDK 8 and 11 windows builds are LTS versions.
Does this also apply to the other platforms listed under 'Other Downloads', or are those only non-LTS builds?
This is unclear to us, please clarify. Especially for the Linux ARM 32 builds we would like to know.
Thanks in advance!

**Comment by ojdkbuild** [comment]
Hi,

x86_64 jdk8 and jdk11 windows builds are LTS, their support lifetime is tied to the lifetime of the corresponding linux version in RHEL.

x86 jdk8 windows build is planned to be built as long as x86_64 version is being built, it may be dropped earlier if some serious 32-bit only problems appear.

Linux x86_64 and ARM32 builds are pure upstream, there are no patches/changes applied to them in this project. They are going to be built as long as upstream repositories are being updated (so there is no explicit EOL date).

Hope this clarifies it.

**Comment by mpe85** [comment]
Thanks for the quick and detailed answer!

**Comment by ojdkbuild** [comment]
Closing the issue.
