### ISSUE TITLE
Debug symbols

### ISSUE THREAD

**Issue by h0nIg** [ojdkbuild/ojdkbuild#7]
Hey,

could you please provide debug symbols within the build?

**Comment by ojdkbuild** [comment]
Yes, debug-related stuff is planned but not yet implemented. Maybe you'll have comments on the debug features that are interesting to you - PDB debug symbols for release binaries, additional full-debug build (bundled with debuggable version of msvcr and with hotspot built in "slowdebug" mode), full sources for java part debugging etc?

**Comment by quijote** [comment]
As a first step, just including the PDB for bin/server/jvm.dll in the ZIP distribution would already be very helpful.

**Comment by ojdkbuild** [comment]
@quijote , just to note that PDBs for release binaries are available with the latest release as a separate "debug.zip" download ( direct link - https://github.com/ojdkbuild/ojdkbuild/releases/download/1.8.0.111-3/java-1.8.0-openjdk-1.8.0.111-3.b15.ojdkbuild.windows.debug.zip ).

**Comment by quijote** [comment]
Thank you. I overlooked these downloads under the releases section. Maybe they could be listed directly on the homepage. 

The symbols + source code were helpful to profile and analyze the JVM with VerySleepy.

**Comment by ojdkbuild** [comment]
Added debug (slowdebug hotspot + debug msvcr) builds for jdk8:

 - https://github.com/ojdkbuild/ojdkbuild/releases/download/1.8.0.121-1/java-1.8.0-openjdk-debug-1.8.0.121-1.b13.ojdkbuild.windows.x86.zip
 - https://github.com/ojdkbuild/ojdkbuild/releases/download/1.8.0.121-1/java-1.8.0-openjdk-debug-1.8.0.121-1.b13.ojdkbuild.windows.x86_64.zip

Now debug symbols for release builds are going to be included with all releases (jdk8, jdk9, x86_64, x86) and separate debug builds going to be included for jdk8. Currently there is no ETA for debug builds for jdk9.

Closing the issue.
