### ISSUE TITLE
javafx-src.zip missing from openjfx 8 Windows build

### ISSUE THREAD

**Issue by bugabinga** [ojdkbuild/ojdkbuild#72]
Usually OpenJFX comes with a `javafx-src.zip` containing source files for the OpenJFX Java source files.
It is placed parallel to `src.zip`, that comes with OpenJDK builds.

This is a minor inconvenience and this issue should be closed, if it is not trivial to fix.

Thank you for providing these builds!

**Comment by ojdkbuild** [comment]
M, yes, for some reason this `javafx-src.zip` is not included with the OpenJFX "overlay" (set of files dropped on top of jdk) that is produced by OpenJFX build. I think `javafx-src.zip` should be included, going to add it for upcoming 8u212 build.

**Comment by ojdkbuild** [comment]
[Fixed](https://github.com/ojdkbuild/deps_openjfx/commit/76f41a551ca13a74e26093356a586d20ed237526#diff-6654dc8e1afc0303d44cf7e6dc4d01adR22) this, going to be included into 8u212.

**Comment by ojdkbuild** [comment]
`javafx-src.zip` is included with [8u212 release](https://github.com/ojdkbuild/ojdkbuild/releases/tag/1.8.0.212-1) (see openjfx-8.0.202-1.b08 binaries). Closing the issue.

**Comment by bugabinga** [comment]
Thank you, much appreciated.
