### ISSUE TITLE
Should "contrib/ojdkbuild-utils" be listed in jdk8 profiles?

### ISSUE THREAD

**Issue by bugabinga** [ojdkbuild/ojdkbuild#73]
If yes:
```diff
diff --git a/resources/profiles/jdk8_msi.gitmodules.txt b/resources/profiles/jdk8_msi.gitmodules.txt
index 2873844..d2d3edf 100644
--- a/resources/profiles/jdk8_msi.gitmodules.txt
+++ b/resources/profiles/jdk8_msi.gitmodules.txt
@@ -1,5 +1,6 @@
 contrib/itw-launcher
 contrib/update-notifier
+contrib/ojdkbuild-utils
 deps/freetype
 deps/giflib
 deps/icedtea-web
diff --git a/resources/profiles/jdk8_webstart.gitmodules.txt b/resources/profiles/jdk8_webstart.gitmodules.txt
index 64cd29e..51c6a93 100644
--- a/resources/profiles/jdk8_webstart.gitmodules.txt
+++ b/resources/profiles/jdk8_webstart.gitmodules.txt
@@ -1,5 +1,6 @@
 contrib/itw-launcher
 contrib/update-notifier
+contrib/ojdkbuild-utils
 deps/freetype
 deps/giflib
 deps/icedtea-web
diff --git a/resources/profiles/jdk8_zip.gitmodules.txt b/resources/profiles/jdk8_zip.gitmodules.txt
index 9855612..5be4f98 100644
--- a/resources/profiles/jdk8_zip.gitmodules.txt
+++ b/resources/profiles/jdk8_zip.gitmodules.txt
@@ -1,5 +1,6 @@
 contrib/itw-launcher
 contrib/update-notifier
+contrib/ojdkbuild-utils
 deps/freetype
 deps/giflib
 deps/icedtea-web
```

**Comment by ojdkbuild** [comment]
Hi, this `contrib/ojdkbuild-utils` repo is work in progress, it is going to be added to gitmodules files soon.

Generally, for "release" builds (checkout from scratch and build) it is better to use last tagged release versions, that should have all scripts intact. For the "development" builds it may be better to have the whole forest (all submodules) locally (so gitmodules files are not needed).

**Comment by bugabinga** [comment]
> Generally, for "release" builds (checkout from scratch and build) it is better to use last tagged release versions, that should have all scripts intact. For the "development" builds it may be better to have the whole forest (all submodules) locally (so gitmodules files are not needed).

I see.
I think you can paste that paragraph verbatim into the `README.md`.
Very useful.
