### ISSUE TITLE
Download speed is extremely slow.

### ISSUE THREAD

**Issue by rkimsb2** [ojdkbuild/ojdkbuild#78]
IMHO there's something wrong on AWS.

**Comment by ojdkbuild** [comment]
This can be caused by different AWS regions or something like that. It works for me with a normal speed now. Leaving the issue open for some time, if there will be more reports, it may worth contacting github about that.

**Comment by ojdkbuild** [comment]
Closing the issue, assuming it was a temporary AWS glitch.

**Comment by rkimsb2** [comment]
I have one more question. Is the Cloudfront enabled?

**Comment by ojdkbuild** [comment]
Sorry, I don't know what Cloudfront is. I am just uploading the releases to GitHub and everything else about them (AWS/CDN config) is done on GitHub side.
