### ISSUE TITLE
Publish source bundles (zip, tar...)

### ISSUE THREAD

**Issue by mickaelistria** [ojdkbuild/ojdkbuild#8]
It would be nice to publish the source bundles together with the release, as some potential users may need source+binaries to conform to License or IP checks.
Eg https://bugs.eclipse.org/bugs/show_bug.cgi?id=506244

**Comment by ojdkbuild** [comment]
I bundled the sources for 8u111-1 release:

 - https://github.com/ojdkbuild/ojdkbuild/releases/download/1.8.0.111-1/java-1.8.0-openjdk-1.8.0.111-1.b15.ojdkbuild.windows.src.zip
 - https://github.com/ojdkbuild/ojdkbuild/releases/download/1.8.0.111-1/java-1.8.0-openjdk-1.8.0.111-1.b15.ojdkbuild.windows.src.zip.sha256

Bundling is done using "nmake srcbundle" target and basically the same as a result of:

    git clone --recursive https://github.com/ojdkbuild/ojdkbuild.git

but excludes all binary tools. All the sources in the bundle originates from CentOS 7 sources, build scripts that are not from CentOS were written by myself.

Will add source bundles to the following releases too. Closing the issue.

**Comment by mickaelistria** [comment]
Thanks a lot!

**Comment by mickaelistria** [comment]
By the way, do you know whether similar source zips are available for Linux?

**Comment by ojdkbuild** [comment]
For CentOS 6 jdk SRPMs (that contains all the sources and patches) are here: http://vault.centos.org/6.8/updates/Source/SPackages/ , direct link to latest one: http://vault.centos.org/6.8/updates/Source/SPackages/java-1.8.0-openjdk-1.8.0.111-0.b15.el6_8.src.rpm

For CentOS 7 jdk source bundles are here: https://git.centos.org/sources/java-1.8.0-openjdk/c7/ , direct link to latest one: https://git.centos.org/sources/java-1.8.0-openjdk/c7/c32fc4a2f70f097b8726e396cceaad1bdad461b6 (actual name: aarch64-port-jdk8u-aarch64-jdk8u111-b15.tar.xz) and RPM patches are here: https://git.centos.org/summary/rpms!java-1.8.0-openjdk

Just please note, that Linux ZIP bundle that can be downloaded from ojdkbuild main page ( https://github.com/ojdkbuild/ojdkbuild/releases/download/1.8.0.111-1/java-1.8.0-openjdk-1.8.0.111-0.b15.el6_8.x86_64.zip ) is extracted from CentOS 6 with the scripts from here ( https://github.com/ojdkbuild/ojdkbuild/wiki/CentOS6ZipBundle ) , this bundle is NOT a part of ojdkbuild releases - I cannot support it even if I will want to do so, it is maintained by RHEL developers and being imported into CentOS after RHEL releases. You of course can use this bundle for any purpose, but please don't associate it with "ojdkbuild" project to prevent possible confusion.

**Comment by ildar** [comment]
That wasn't a wise decision. Doubling zip size for src.zip is hm... doubtful.
You could simply put a link to the https://github.com/ojdkbuild/ojdkbuild/releases

**Comment by ojdkbuild** [comment]
Hi, @ildar , I think you are confusing `src.zip`, that is included inside MSI and ZIP bundle and a separate sources ZIP bundle that has been requested in this issue.

`src.zip` contains only Java sources that are required for debugging. It is loaded automatically by IDEs. Not including all the Java sources means that excluded packages cannot be debugged. Please see more details in [this thread](http://mail.openjdk.java.net/pipermail/jdk8u-dev/2017-January/006327.html).

Sources bundle requested in this issues ([example](https://github.com/ojdkbuild/ojdkbuild/releases/download/1.8.0.121-2/java-1.8.0-openjdk-1.8.0.121-2.b13.ojdkbuild.windows.src.zip)) contains all the native and Java sources and build scripts that were used to builds the corresponding jdk binaries. It is effectively a partial snapshot of the git repo. Such bundle is useless for normal users, but may be required for legal reasons in projects (like Eclipse) that want to use ojdkbuild binaries.

**Comment by ildar** [comment]
You're right. Sorry for the noise
