### ISSUE TITLE
Instructions do not lead to MSI installer

### ISSUE THREAD

**Issue by robert-scheck** [ojdkbuild/ojdkbuild#81]
I followed https://github.com/ojdkbuild/ojdkbuild/wiki/HowToBuild to build OpenJDK 8, but `nmake installer` did not lead to any `*.msi` and also not to any `*.zip` but did not produce any error message either.

```
[…]
[ 95%] Built target itw_netx
Scanning dependencies of target icedtea_web
[ 95%] Creating icedtea_web distribution, path: [C:/ojdkbuild/build/icedtea_web/dist] ...

                                C:\ojdkbuild\build\icedtea_web\javaws.jar

                                C:\ojdkbuild\build\bin\javaws.exe

                                C:\ojdkbuild\build\icedtea_web\itw_launcher\javaws_options.txt

                                C:\ojdkbuild\lookaside\icedtea-web\netx\javaws_splash.png
[ 95%] Built target icedtea_web
Scanning dependencies of target debuginfo
[ 95%] Creating debuginfo bundle ...

                                C:\ojdkbuild\build\java-1.8.0-openjdk-1.8.0.212-0.b04.ojdkbuild.windows.x86_64.debuginfo.zip
[ 95%] Built target debuginfo
Scanning dependencies of target image_itw
[ 95%] Adding IcedTea-Web to image ...

                                C:\ojdkbuild\build\icedtea_web\dist\javaws.exe
                                C:\ojdkbuild\build\icedtea_web\dist\javaws.jar
                                C:\ojdkbuild\build\icedtea_web\dist\javaws_options.txt
                                C:\ojdkbuild\build\icedtea_web\dist\javaws_splash.png
[ 95%] Built target image_itw
Scanning dependencies of target zip
[ 95%] Creating ZIP bundle ...

                                C:\ojdkbuild\build\java-1.8.0-openjdk-1.8.0.212-0.b04.ojdkbuild.windows.x86_64.zip
[ 95%] Built target zip
Scanning dependencies of target installer_bundle_contents_webstart
[ 95%] Preparing MSI WebStart installer bundle ...



[ 95%] Built target installer_bundle_contents_webstart
Scanning dependencies of target installer_bundle_webstart
[100%] Creating MSI WebStart installer bundle ...

                                C:\ojdkbuild\build\java-1.8.0-openjdk-1.8.0.212-0.b04.ojdkbuild.windows.x86_64.installer_bundle.zip
[100%] Built target installer_bundle_webstart
Scanning dependencies of target installer
[100%] Creating MSI installer ...
java-1.8.0-openjdk-1.8.0.212-0.b04.ojdkbuild.windows.x86_64.wxs

                                C:\ojdkbuild\build\java-1.8.0-openjdk-1.8.0.212-0.b04.ojdkbuild.windows.x86_64.installer_bundle\java-1.8.0-openjdk-1.8.0.212-0.b04.ojdkbuild.windows.x86_64.msi
[100%] Built target installer

Administrator@OJDKBUILD C:\ojdkbuild\build
#

```

So there are no `C:\ojdkbuild\build\java-1.8.0-openjdk-1.8.0.212-0.b04.ojdkbuild.windows.x86_64.installer_bundle\java-1.8.0-openjdk-1.8.0.212-0.b04.ojdkbuild.windows.x86_64.msi` and `C:\ojdkbuild\build\java-1.8.0-openjdk-1.8.0.212-0.b04.ojdkbuild.windows.x86_64.zip` files.

Not sure if it helps to figure out the cause, but `<jdk>.installer_bundle` does also not contain any `<jdk>.wix` here (this might be a documentation mistake however, given `CMakeLists.txt` says `<jdk>.wxs` rather `<jdk>.wix`).

Just running manually after `nmake installer` the steps `cd <jdk>.installer_bundle` and `..\..\tools\wix\bin\light -sw1076 -ext WixUIExtension -ext WixUtilExtension <jdk>.wixobj ` however leads to a proper `*.msi`. So what's wrong?

**Comment by ojdkbuild** [comment]
Can you check `<ojdkbuild>/dist directory`, it should contain both ZIP and MSI? On a second though I wonder, what will happen if this dir is not pre-created (this is probably a bug - will check this). If dist dir is not created for you - please create it manually an run `nmake installer` again from the same build dir.

On `.wix` vs `.wxs`: thanks for that note, yes, it was a mistake in doc, just fixed it.

**Comment by ojdkbuild** [comment]
Also, if you are building installer with some customizations, you may want to also adjust the installer art/icons, it can be done specifying `-Dopenjdk_INSTALLER_RESOURCES_PATH=path/to/instres_dir`  that should point to [directory with custom art](https://github.com/ojdkbuild/ojdkbuild/tree/master/resources/installer/instres). Of course, please feel free to use default art too.

**Comment by robert-scheck** [comment]
> Can you check `<ojdkbuild>/dist directory`, it should contain both ZIP and MSI?

Yes, that directory contains `*.zip`, `*.msi`, `*.installer_bundle.zip` and `*.debuginfo.zip`. Is it intended that these files end in `<ojdkbuild>/dist` directory? Based on make output, I expected them somewhere else ;-)

**Comment by ojdkbuild** [comment]
Yes, that may be confusing, other dir can be specified with `-Dopenjdk_DEST_DIR=path/to/dir` option.

**Comment by robert-scheck** [comment]
I see, thank you. It could make sense to add such hints to the build howto.

**Comment by ojdkbuild** [comment]
Added a note about the destination dir option, closing the issue.
