### ISSUE TITLE
Readme.md of tag 1.8.0.212-1 points to 1.8.0_201-1 downloads

### ISSUE THREAD

**Issue by btreut** [ojdkbuild/ojdkbuild#82]
the links in [README.md](https://github.com/ojdkbuild/ojdkbuild/blob/1.8.0.212-1/README.md) of tag 1.8.0.212-1 still point to the downloads of tag 1.8.0_201-1 and the changelog end 25-Jan-2019.

**Comment by ojdkbuild** [comment]
Yes, readme is updated after the releases (and tags for them) are created. Currently the process is the following:

1. create github release (also creates a tag) and upload binaries

2. write the announce email (with the link to release)

3. update the readme (with the link to announce)

So the release tag includes up to date sources and binaries for that release, but a stale readme.

**Comment by btreut** [comment]
thanks, do I understand correctly: the release process is stuck currently between step 2. and 3.

**Comment by ojdkbuild** [comment]
No, April release is done, and [readme was updated](https://github.com/ojdkbuild/ojdkbuild/commit/2b269101b9317eeca6c897975657fbebf7851916), just such updates land in the subsequent commits after the tag.

**Comment by btreut** [comment]
>  includes up to date sources and binaries for that release, but a stale readme.

and this stays intentionally so. Then it was my misconception about a tag that its README.md should reflect the download links pointing to the tagged release.

**Comment by ojdkbuild** [comment]
Closing the issue.
