### ISSUE TITLE
Feature 'webstart_env' and 'webstart_migrate' share same feature level variable like 'webstart'

### ISSUE THREAD

**Issue by robert-scheck** [ojdkbuild/ojdkbuild#83]
As per

 - https://github.com/ojdkbuild/deps_icedtea-web/blob/master/resources/installer.xsl#L105
 - https://github.com/ojdkbuild/deps_icedtea-web/blob/master/resources/installer.xsl#L114
 - https://github.com/ojdkbuild/deps_icedtea-web/blob/master/resources/installer.xsl#L128
 - https://github.com/ojdkbuild/deps_icedtea-web/blob/master/resources/installer.xsl#L135

the features `webstart`, `webstart_registry`, `webstart_env`, `webstart_migrate` share the same feature level variable, thus they just can be turned off and on together. From my point of view, there is a valid scenario where only `webstart` and `webstart_registry` could make sense (e.g. if you would like to just provide icedtea-web for `*.jnlp` handling). Would it thus make sense to use different variables for finely granulated options during build-time - or am I overlooking something?

**Comment by ojdkbuild** [comment]
[moved the issue to parent repo]

Yes, this is a valid concern. Nothing prevents the user to select different set of features during install-time, but it is currently not possible to build the installer with different default levels for `webstart_` features. It won't harm making them more granular, going to do so.

**Comment by ojdkbuild** [comment]
Added [more config variables](https://github.com/ojdkbuild/deps_icedtea-web/commit/33aa920de10c79bf710482bf77405563d8bfaa49), now there are 4 of them: 

`icedtea_web_INSTALLER_FEATURE_LEVEL`
`icedtea_web_INSTALLER_FEATURE_LEVEL_REGISTRY`
`icedtea_web_INSTALLER_FEATURE_LEVEL_ENV`
`icedtea_web_INSTALLER_FEATURE_LEVEL_MIGRATE`

**Comment by ojdkbuild** [comment]
This has been implemented, closing the issue.
