### ISSUE TITLE
webstart crashes when user name contains space (MS Windows 10)

### ISSUE THREAD

**Issue by btreut** [ojdkbuild/ojdkbuild#84]
A windows user name containing a space causes javaws to crash with a "Fatal Launch Error: Could not launch JNLP file. The application has not been initialized ...". Admitted that it is not a really good idea to have user names containing spaces, it happened to be the case in the field and it was a little bit ugly to boil the problems down to the space in the user name and I was able to reproduce it with a user "Test Test".

The %userprofile%\AppData\..\ojdkbuil\..\javaws_last_log.txt contains:
Starting Netx, command: ["C:/Program Files/ojdkbuild/java-1.8.0-openjdk-1.8.0.212-1/webstart/../bin/java.exe" -XX:+TieredCompilation -XX:TieredStopAtLevel=1 -XX:+UseSerialGC -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -splash:"C:/Program Files/ojdkbuild/java-1.8.0-openjdk-1.8.0.212-1/webstart/javaws_splash.png" -Xbootclasspath/a:"C:/Program Files/ojdkbuild/java-1.8.0-openjdk-1.8.0.212-1/webstart/javaws.jar" -classpath "C:/Program Files/ojdkbuild/java-1.8.0-openjdk-1.8.0.212-1/webstart/../jre/lib/rt.jar" -Ditw.userdata="C:/Users/Test Test/AppData/Local/ojdkbuild/java-1.8.0-openjdk-1.8.0.212-1.b04.ojdkbuild.windows.x86_64/webstart/" -Dicedtea-web.bin.name=javaws.exe -Dicedtea-web.bin.location="C:/Program Files/ojdkbuild/java-1.8.0-openjdk-1.8.0.212-1/webstart/javaws.exe" net.sourceforge.jnlp.runtime.Boot -Xnofork -helpurl="https://github.com/ojdkbuild/ojdkbuild/wiki/WebStart" "C:\Users\TESTTE~1\AppData\Local\Temp\qisfsv3t.jnlp"]
Property "deployment.expiration.check.enabled" is unknown.
Property "deployment.security.level" has incorrect value "HIGH". Possible values DENY_ALL DENY_UNSIGNED ASK_UNSIGNED ALLOW_UNSIGNED.
java.net.URISyntaxException: Illegal character in path at index 20: file://C:/Users/Test Test/AppData/Local/ojdkbuild/java-1.8.0-openjdk-1.8.0.212-1.b04.ojdkbuild.windows.x86_64/webstart/.config/icedtea-web/security/java.policy
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3105)
	at java.net.URI$Parser.parse(URI.java:3053)
	at java.net.URI.<init>(URI.java:588)
	at net.sourceforge.jnlp.runtime.JNLPPolicy.getPolicyFromUrl(JNLPPolicy.java:188)
	at net.sourceforge.jnlp.runtime.JNLPPolicy.<init>(JNLPPolicy.java:64)
	at net.sourceforge.jnlp.runtime.JNLPRuntime.initialize(JNLPRuntime.java:260)
	at net.sourceforge.jnlp.runtime.Boot.init(Boot.java:349)
	at net.sourceforge.jnlp.runtime.JnlpBoot.run(JnlpBoot.java:58)
	at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:270)
	at net.sourceforge.jnlp.runtime.Boot.run(Boot.java:64)
	at java.security.AccessController.doPrivileged(Native Method)
	at net.sourceforge.jnlp.runtime.Boot.main(Boot.java:210)

Codebase matches codebase manifest attribute, and application is signed. Continuing. See: http://docs.oracle.com/javase/7/docs/technotes/guides/jweb/security/no_redeploy.html for details.
Starting application [de.his.fsv.mbs.qisfsv3t.client.gui.StartApplet] ...
netx: Launch Error: Could not launch JNLP file. (de.his.fsv.mbs.qisfsv3t.client.gui.StartApplet)
net.sourceforge.jnlp.LaunchException: Fatal: Launch Error: Could not launch JNLP file. The application has not been initialized, for more information execute javaws/browser from the command line and send a bug report.
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:582)
	at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:945)
Caused by: java.lang.ClassNotFoundException: de.his.fsv.mbs.qisfsv3t.client.gui.StartApplet
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.loadClass(JNLPClassLoader.java:1640)
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:556)
	... 1 more

**Comment by ojdkbuild** [comment]
Thanks for the report! From the log it looks like the launcher is doing its job correctly, but ITW itself is failing due to something like missed URI escaping. I will look into it.

**Comment by ojdkbuild** [comment]
Seems to fixed this with [some URI fixes](https://github.com/ojdkbuild/lookaside_icedtea-web/commit/2bdab79a9d6dd3d5286c834365716c47876f1a17), at least I can run a JNLP from `Test Test` now. 
Uploaded a [fixed version](https://github.com/ojdkbuild/ojdkbuild/files/3154726/javaws.jar.zip), it would be great if you could try it with your app.

**Comment by btreut** [comment]
thanks Alex (?), it looks good and the applet starts via JNLP downloaded by FireFox and works apparenlty without problems with the new javaws.jar.

**Comment by ojdkbuild** [comment]
Thanks for checking! I don't want to do another 8u212 release with this fix, so uploaded [x86_64](https://drive.google.com/open?id=16gGCWDGsB_Gc3c7I1o1Gl5XinDvnHi2s) and [x86](https://drive.google.com/open?id=1TOiLmfaisUWqtwoAgmOAIdVJ2Dx5zS0w) installers with this fix to temporary location instead (going to keep them until 8u222 release).

**Comment by ojdkbuild** [comment]
The fix is included with 8u222, closing the issue.
