### ISSUE TITLE
Run ojdkbuild java plugin in internet explorer 

### ISSUE THREAD

**Issue by wanderleihuttel** [ojdkbuild/ojdkbuild#86]
Hello 
Is possible to activate java plugin using ojdkbuild in Internet Explorer ?
Here in Brazil there is a government (https://conectividade.caixa.gov.br) that still need to execute Java as applet, and not working with java ojdkbuild.

**Comment by ojdkbuild** [comment]
Hi, no, unfortunately that is not possible:

1. Oracle Java Browser Plugin was never open sourced

2. Browsers are actively disabling the Plugin API that was used by Java Plugin (no modern browsers support it)

3. IcedTea-Web (that is used in ojdkbuild for WebStart) had a Browser Plugin in the past, but it was available only for Linux

4. There exists a partial support to run applets as standalone WebStart applications using:

    javaws --html http://some/html/page.html

but this method is unlikely to work on real-life applets - it requires the page to be quite simple (to parse it) and requires the applet to not interact with Browser APIs.

**Comment by btreut** [comment]
it should be possible to use jnlp to start the applet. We switchet some years ago from a pure applet running in the browser to start that applet via jnlp.

**Comment by ojdkbuild** [comment]
Closing this as "answered", it is hard to do something about the applets.
