### ISSUE TITLE
JDK 11 awt.dll depends on d2d1.dll but it is not distributed

### ISSUE THREAD

**Issue by slide** [ojdkbuild/ojdkbuild#88]
Not sure if this is really an issue here, but when trying to run a docker image that depends on openjdk 11 and needs AWT, there is a problem that d2d1.dll is not present in the image. It is not there in the windowsservercore image and is not distributed by the openjdk zip that is COPY'd into the container. I am opening the issue here because it seems like all other dependencies are present in the zip file except for d2d1.dll. 

It would be nice to get d2d1.dll included in the zip for JDK versions that require it (I have not looked at JDK 12 or JDK 13 builds, but they probably have a similar dependency for AWT).

**Comment by ojdkbuild** [comment]
Thanks for the report! Indeed Direct2D is not included with official windowsservercore image. And AWT may be needed in headless environment sometimes. I'll look into more details about this.

**Comment by ojdkbuild** [comment]
The fix for this from [JDK-8229800](https://bugs.openjdk.java.net/browse/JDK-8229800) is included into both upcoming 11.0.5 and 13.0.1 builds.

**Comment by ojdkbuild** [comment]
11.0.5 and 13.0.1 are published now, closing the issue.
