### ISSUE TITLE
Unable to install *.msi on Windows

### ISSUE THREAD

**Issue by SmallJoker** [ojdkbuild/ojdkbuild#9]
Msiexec version: V 4.5.6001
Windows version: 5.1.2600 (XP)

Error message: `This installer packet is not supported on this Platform. Please contact [...]`

**Comment by ojdkbuild** [comment]
Win7+ is officially supported, but it almost certainly works on Vista and should work on 2003/XP too. At least it works for me on 2003 with win version `5.2.3790`.

Of course only 64-bit OS will work until #2 will be fixed (in progress).

**Comment by ojdkbuild** [comment]
Worked for me on XP too (it shows the same win version as 2003 checked before - `5.2.3790`). After quick search I couldn't find windows version for x86_64 with `5.1.2600` version number. Closing as `works for me`. If it will be needed - please reopen with more details.

**Comment by SmallJoker** [comment]
Indeed, I use the 32-bit version and assumed x86_64 would include support for both architectures.
Thanks for pointing out issue 2. I must have overseen that one or thought it was outdated or inactive. Keep up the good work :+1:
