### ISSUE TITLE
include system architecture to package in control panel

### ISSUE THREAD

**Issue by gituser317** [ojdkbuild/ojdkbuild#90]
On Windows systems which have both the x86 and the x64 installed, in control panel the name of both installations is the same - for example OpenJDK 1.8.0_212-0-ojdkbuild.
Please add a marker for system architecture - for example OpenJDK 1.8.0_212-0-ojdkbuild-x64.
Thank you.

**Comment by ojdkbuild** [comment]
Hi, I think this can be done, going to add a `-x86` suffix for 32-bit builds.

**Comment by gituser317** [comment]
Hi, that would be great. Many thanks!

**Comment by ojdkbuild** [comment]
Just FYI, this is included into upcoming 8u232 build. 64-bit labels are left the same, `-x86` suffix added to 32-bit labels.

**Comment by ojdkbuild** [comment]
Fixed in 8u232, closing the issue.
