### ISSUE TITLE
I just want to say "Thank you"

### ISSUE THREAD

**Issue by Gordon-Dry** [ojdkbuild/ojdkbuild#93]
Thank you.
Honestly.

I still had jre-8u221-windows-x64 on my system, now a software package was updated and claimed that it depends on Java 11 now.

The "normal" Java 11 and 12 downloads were not install-able.
jdk-11.0.3_windows-x64_bin.exe MD5 94509fdca7dd948673392ca85b913848
jdk-12.0.2_windows-x64_bin.exe MD5 068469165a8998ec5d4b76f8cfd9147c

Yes, I uninstalled old Java. Yes, I even rebooted Windows 10. Yes, I even disabled AV software.

But no avail, after launching the installer .exe there was a short twitch and 1 sec of an "hourglass cursor" but then the process finished itself again ...

I really was getting annoyed.

Finally I stumbled upon your solution.

1. Quick install, not the everlasting bs the original installer was (JRE 8! only JRE! even slower!)
2. The software now just works without complaining in a popup message.

Thank you.

P.S.

That "stock" Java is not even capable of being installed is really a disappointment to the fullest. Shame on you, Oracle.

I don't typically misuse the Github issues to say "thank you"...

**Comment by Gordon-Dry** [comment]
I will close this tomorrow if you want.
You can even do it right now.
No problem.

**Comment by ojdkbuild** [comment]
You are welcome!
