### ISSUE TITLE
OpenJFX not included in the OpenJDK8 JREs

### ISSUE THREAD

**Issue by jschwartzenberg** [ojdkbuild/ojdkbuild#94]
I just noticed that OpenJFX is not included in the JREs. Would it be possible to include this or should users also obtain the OpenJFX zips and extract those over the JREs?

**Comment by ojdkbuild** [comment]
Yes, it is not included deliberately. JRE download is intended to be minimal in size, and OpenJFX is quite big, `jfxwebkit.dll` alone is 62 MBs. Unpacking `jre` dir from `openjfx-` ZIP bundle on top of JRE should work.

**Comment by jschwartzenberg** [comment]
Indeed that works fine. Thanks for the info!
