### ISSUE TITLE
Suggestion: 2x JVM Path parameter for x86 and x64

### ISSUE THREAD

**Issue by patris70** [ojdkbuild/ojdkbuild#98]
Hi,

Icedtea-Web has just one JVM Path Parameter (deployment.jre.dir).
The problem is, Some Programs need java x86 version and some x64. If i set deployment.jre.dir with target x64 version path,, program fails, because program needs java x86 but java x64 started.

My Suggestion is, we need 2x JVM Path:
for **x64** Version ===> deployment.jre**64**.dir
for **x86** Version ===> deployment.jre**32**.dir 

As Info: Oracle Java uses:
deployment.javaws.jre.**0**.path
deployment.javaws.jre.**1**.path
 
Thanks

**Comment by ojdkbuild** [comment]
Sorry, don't want to add any changes specific to 32-bit version. It is better to use 64-bit version where possible. And mixing versions with the same cache/settings it definitely not supported.  Closing as "won't fix".
