### ISSUE TITLE
fixed User Keystore Password Prompt

### ISSUE THREAD

**Issue by patris70** [ojdkbuild/ojdkbuild#99]
Hi,

If user previously used Oracle Java and also had user keystore, Icedtea-Web gets KeyStore Password popup window, because Oracle Java does not set password for user keystore.
Here is fix:

**Updates to net/sourceforge/jnlp/security/KeystorePasswordAttempter.java**
Change Line 128
**From:**

`static final KeystorePasswordAttempter INSTANCE = new KeystorePasswordAttempter(new SavedPassword(getTrustedCertsPassword()));`

**To:**

`static final KeystorePasswordAttempter INSTANCE = new KeystorePasswordAttempter(new SavedPassword(getTrustedCertsPassword()), new SavedPassword("".toCharArray()));`

**Comment by ojdkbuild** [comment]
Fix is [added](https://github.com/ojdkbuild/lookaside_icedtea-web/commit/b564da2d37b4c8a53779cd051a958fa76328d65a) now and going to be included into 8u232 build. You may also consider bringing it to `AdoptOpenJDK/IcedTea-Web`.

**Comment by ojdkbuild** [comment]
Fixed in 8u232, closing the issue.
